// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterface"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterfacelink"
)

// DeviceInterfaceLink is the model entity for the DeviceInterfaceLink schema.
type DeviceInterfaceLink struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// Owning local interface ID
	InterfaceID string `json:"interface_id,omitempty"`
	// Connected neighbor device ID (e.g. the switch this port plugs into)
	RemoteDeviceID string `json:"remote_device_id,omitempty"`
	// Connected neighbor interface ID (e.g. the switch port)
	RemoteInterfaceID string `json:"remote_interface_id,omitempty"`
	// Connected neighbor port name (denormalized for display)
	RemotePortName string `json:"remote_port_name,omitempty"`
	// How the link was discovered: snmp_fdb, lldp, manual
	LinkSource string `json:"link_source,omitempty"`
	// VLAN the neighbor MAC was learned on (Q-BRIDGE FDB)
	LinkVlan *int32 `json:"link_vlan,omitempty"`
	// When the neighbor link was last observed
	LinkLastSeen *time.Time `json:"link_last_seen,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceInterfaceLinkQuery when eager-loading is set.
	Edges        DeviceInterfaceLinkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceInterfaceLinkEdges holds the relations/edges for other nodes in the graph.
type DeviceInterfaceLinkEdges struct {
	// Interface holds the value of the interface edge.
	Interface *DeviceInterface `json:"interface,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InterfaceOrErr returns the Interface value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceInterfaceLinkEdges) InterfaceOrErr() (*DeviceInterface, error) {
	if e.Interface != nil {
		return e.Interface, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: deviceinterface.Label}
	}
	return nil, &NotLoadedError{edge: "interface"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceInterfaceLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deviceinterfacelink.FieldLinkVlan:
			values[i] = new(sql.NullInt64)
		case deviceinterfacelink.FieldID, deviceinterfacelink.FieldInterfaceID, deviceinterfacelink.FieldRemoteDeviceID, deviceinterfacelink.FieldRemoteInterfaceID, deviceinterfacelink.FieldRemotePortName, deviceinterfacelink.FieldLinkSource:
			values[i] = new(sql.NullString)
		case deviceinterfacelink.FieldCreateTime, deviceinterfacelink.FieldUpdateTime, deviceinterfacelink.FieldDeleteTime, deviceinterfacelink.FieldLinkLastSeen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceInterfaceLink fields.
func (_m *DeviceInterfaceLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deviceinterfacelink.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case deviceinterfacelink.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case deviceinterfacelink.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case deviceinterfacelink.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case deviceinterfacelink.FieldInterfaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field interface_id", values[i])
			} else if value.Valid {
				_m.InterfaceID = value.String
			}
		case deviceinterfacelink.FieldRemoteDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_device_id", values[i])
			} else if value.Valid {
				_m.RemoteDeviceID = value.String
			}
		case deviceinterfacelink.FieldRemoteInterfaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_interface_id", values[i])
			} else if value.Valid {
				_m.RemoteInterfaceID = value.String
			}
		case deviceinterfacelink.FieldRemotePortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remote_port_name", values[i])
			} else if value.Valid {
				_m.RemotePortName = value.String
			}
		case deviceinterfacelink.FieldLinkSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_source", values[i])
			} else if value.Valid {
				_m.LinkSource = value.String
			}
		case deviceinterfacelink.FieldLinkVlan:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field link_vlan", values[i])
			} else if value.Valid {
				_m.LinkVlan = new(int32)
				*_m.LinkVlan = int32(value.Int64)
			}
		case deviceinterfacelink.FieldLinkLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field link_last_seen", values[i])
			} else if value.Valid {
				_m.LinkLastSeen = new(time.Time)
				*_m.LinkLastSeen = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceInterfaceLink.
// This includes values selected through modifiers, order, etc.
func (_m *DeviceInterfaceLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInterface queries the "interface" edge of the DeviceInterfaceLink entity.
func (_m *DeviceInterfaceLink) QueryInterface() *DeviceInterfaceQuery {
	return NewDeviceInterfaceLinkClient(_m.config).QueryInterface(_m)
}

// Update returns a builder for updating this DeviceInterfaceLink.
// Note that you need to call DeviceInterfaceLink.Unwrap() before calling this method if this DeviceInterfaceLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeviceInterfaceLink) Update() *DeviceInterfaceLinkUpdateOne {
	return NewDeviceInterfaceLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeviceInterfaceLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeviceInterfaceLink) Unwrap() *DeviceInterfaceLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceInterfaceLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeviceInterfaceLink) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceInterfaceLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("interface_id=")
	builder.WriteString(_m.InterfaceID)
	builder.WriteString(", ")
	builder.WriteString("remote_device_id=")
	builder.WriteString(_m.RemoteDeviceID)
	builder.WriteString(", ")
	builder.WriteString("remote_interface_id=")
	builder.WriteString(_m.RemoteInterfaceID)
	builder.WriteString(", ")
	builder.WriteString("remote_port_name=")
	builder.WriteString(_m.RemotePortName)
	builder.WriteString(", ")
	builder.WriteString("link_source=")
	builder.WriteString(_m.LinkSource)
	builder.WriteString(", ")
	if v := _m.LinkVlan; v != nil {
		builder.WriteString("link_vlan=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LinkLastSeen; v != nil {
		builder.WriteString("link_last_seen=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DeviceInterfaceLinks is a parsable slice of DeviceInterfaceLink.
type DeviceInterfaceLinks []*DeviceInterfaceLink
