// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/devicepackage"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// DevicePackageUpdate is the builder for updating DevicePackage entities.
type DevicePackageUpdate struct {
	config
	hooks     []Hook
	mutation  *DevicePackageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DevicePackageUpdate builder.
func (_u *DevicePackageUpdate) Where(ps ...predicate.DevicePackage) *DevicePackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DevicePackageUpdate) SetUpdateTime(v time.Time) *DevicePackageUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableUpdateTime(v *time.Time) *DevicePackageUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DevicePackageUpdate) ClearUpdateTime() *DevicePackageUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DevicePackageUpdate) SetDeleteTime(v time.Time) *DevicePackageUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableDeleteTime(v *time.Time) *DevicePackageUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DevicePackageUpdate) ClearDeleteTime() *DevicePackageUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DevicePackageUpdate) SetDeviceID(v string) *DevicePackageUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableDeviceID(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DevicePackageUpdate) SetName(v string) *DevicePackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableName(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *DevicePackageUpdate) SetCurrentVersion(v string) *DevicePackageUpdate {
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableCurrentVersion(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// ClearCurrentVersion clears the value of the "current_version" field.
func (_u *DevicePackageUpdate) ClearCurrentVersion() *DevicePackageUpdate {
	_u.mutation.ClearCurrentVersion()
	return _u
}

// SetAvailableVersion sets the "available_version" field.
func (_u *DevicePackageUpdate) SetAvailableVersion(v string) *DevicePackageUpdate {
	_u.mutation.SetAvailableVersion(v)
	return _u
}

// SetNillableAvailableVersion sets the "available_version" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableAvailableVersion(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetAvailableVersion(*v)
	}
	return _u
}

// ClearAvailableVersion clears the value of the "available_version" field.
func (_u *DevicePackageUpdate) ClearAvailableVersion() *DevicePackageUpdate {
	_u.mutation.ClearAvailableVersion()
	return _u
}

// SetNeedsUpdate sets the "needs_update" field.
func (_u *DevicePackageUpdate) SetNeedsUpdate(v bool) *DevicePackageUpdate {
	_u.mutation.SetNeedsUpdate(v)
	return _u
}

// SetNillableNeedsUpdate sets the "needs_update" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableNeedsUpdate(v *bool) *DevicePackageUpdate {
	if v != nil {
		_u.SetNeedsUpdate(*v)
	}
	return _u
}

// SetIsSecurityUpdate sets the "is_security_update" field.
func (_u *DevicePackageUpdate) SetIsSecurityUpdate(v bool) *DevicePackageUpdate {
	_u.mutation.SetIsSecurityUpdate(v)
	return _u
}

// SetNillableIsSecurityUpdate sets the "is_security_update" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableIsSecurityUpdate(v *bool) *DevicePackageUpdate {
	if v != nil {
		_u.SetIsSecurityUpdate(*v)
	}
	return _u
}

// SetPackageManager sets the "package_manager" field.
func (_u *DevicePackageUpdate) SetPackageManager(v string) *DevicePackageUpdate {
	_u.mutation.SetPackageManager(v)
	return _u
}

// SetNillablePackageManager sets the "package_manager" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillablePackageManager(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetPackageManager(*v)
	}
	return _u
}

// ClearPackageManager clears the value of the "package_manager" field.
func (_u *DevicePackageUpdate) ClearPackageManager() *DevicePackageUpdate {
	_u.mutation.ClearPackageManager()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DevicePackageUpdate) SetDescription(v string) *DevicePackageUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DevicePackageUpdate) SetNillableDescription(v *string) *DevicePackageUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DevicePackageUpdate) ClearDescription() *DevicePackageUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the DevicePackageMutation object of the builder.
func (_u *DevicePackageUpdate) Mutation() *DevicePackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DevicePackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DevicePackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DevicePackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DevicePackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DevicePackageUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := devicepackage.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := devicepackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentVersion(); ok {
		if err := devicepackage.CurrentVersionValidator(v); err != nil {
			return &ValidationError{Name: "current_version", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.current_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableVersion(); ok {
		if err := devicepackage.AvailableVersionValidator(v); err != nil {
			return &ValidationError{Name: "available_version", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.available_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageManager(); ok {
		if err := devicepackage.PackageManagerValidator(v); err != nil {
			return &ValidationError{Name: "package_manager", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.package_manager": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DevicePackageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DevicePackageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DevicePackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicepackage.Table, devicepackage.Columns, sqlgraph.NewFieldSpec(devicepackage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(devicepackage.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(devicepackage.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(devicepackage.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(devicepackage.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(devicepackage.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(devicepackage.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(devicepackage.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(devicepackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(devicepackage.FieldCurrentVersion, field.TypeString, value)
	}
	if _u.mutation.CurrentVersionCleared() {
		_spec.ClearField(devicepackage.FieldCurrentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.AvailableVersion(); ok {
		_spec.SetField(devicepackage.FieldAvailableVersion, field.TypeString, value)
	}
	if _u.mutation.AvailableVersionCleared() {
		_spec.ClearField(devicepackage.FieldAvailableVersion, field.TypeString)
	}
	if value, ok := _u.mutation.NeedsUpdate(); ok {
		_spec.SetField(devicepackage.FieldNeedsUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSecurityUpdate(); ok {
		_spec.SetField(devicepackage.FieldIsSecurityUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PackageManager(); ok {
		_spec.SetField(devicepackage.FieldPackageManager, field.TypeString, value)
	}
	if _u.mutation.PackageManagerCleared() {
		_spec.ClearField(devicepackage.FieldPackageManager, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(devicepackage.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(devicepackage.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DevicePackageUpdateOne is the builder for updating a single DevicePackage entity.
type DevicePackageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DevicePackageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *DevicePackageUpdateOne) SetUpdateTime(v time.Time) *DevicePackageUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableUpdateTime(v *time.Time) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DevicePackageUpdateOne) ClearUpdateTime() *DevicePackageUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DevicePackageUpdateOne) SetDeleteTime(v time.Time) *DevicePackageUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableDeleteTime(v *time.Time) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DevicePackageUpdateOne) ClearDeleteTime() *DevicePackageUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DevicePackageUpdateOne) SetDeviceID(v string) *DevicePackageUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableDeviceID(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DevicePackageUpdateOne) SetName(v string) *DevicePackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableName(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrentVersion sets the "current_version" field.
func (_u *DevicePackageUpdateOne) SetCurrentVersion(v string) *DevicePackageUpdateOne {
	_u.mutation.SetCurrentVersion(v)
	return _u
}

// SetNillableCurrentVersion sets the "current_version" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableCurrentVersion(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetCurrentVersion(*v)
	}
	return _u
}

// ClearCurrentVersion clears the value of the "current_version" field.
func (_u *DevicePackageUpdateOne) ClearCurrentVersion() *DevicePackageUpdateOne {
	_u.mutation.ClearCurrentVersion()
	return _u
}

// SetAvailableVersion sets the "available_version" field.
func (_u *DevicePackageUpdateOne) SetAvailableVersion(v string) *DevicePackageUpdateOne {
	_u.mutation.SetAvailableVersion(v)
	return _u
}

// SetNillableAvailableVersion sets the "available_version" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableAvailableVersion(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetAvailableVersion(*v)
	}
	return _u
}

// ClearAvailableVersion clears the value of the "available_version" field.
func (_u *DevicePackageUpdateOne) ClearAvailableVersion() *DevicePackageUpdateOne {
	_u.mutation.ClearAvailableVersion()
	return _u
}

// SetNeedsUpdate sets the "needs_update" field.
func (_u *DevicePackageUpdateOne) SetNeedsUpdate(v bool) *DevicePackageUpdateOne {
	_u.mutation.SetNeedsUpdate(v)
	return _u
}

// SetNillableNeedsUpdate sets the "needs_update" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableNeedsUpdate(v *bool) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetNeedsUpdate(*v)
	}
	return _u
}

// SetIsSecurityUpdate sets the "is_security_update" field.
func (_u *DevicePackageUpdateOne) SetIsSecurityUpdate(v bool) *DevicePackageUpdateOne {
	_u.mutation.SetIsSecurityUpdate(v)
	return _u
}

// SetNillableIsSecurityUpdate sets the "is_security_update" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableIsSecurityUpdate(v *bool) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetIsSecurityUpdate(*v)
	}
	return _u
}

// SetPackageManager sets the "package_manager" field.
func (_u *DevicePackageUpdateOne) SetPackageManager(v string) *DevicePackageUpdateOne {
	_u.mutation.SetPackageManager(v)
	return _u
}

// SetNillablePackageManager sets the "package_manager" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillablePackageManager(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetPackageManager(*v)
	}
	return _u
}

// ClearPackageManager clears the value of the "package_manager" field.
func (_u *DevicePackageUpdateOne) ClearPackageManager() *DevicePackageUpdateOne {
	_u.mutation.ClearPackageManager()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DevicePackageUpdateOne) SetDescription(v string) *DevicePackageUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DevicePackageUpdateOne) SetNillableDescription(v *string) *DevicePackageUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DevicePackageUpdateOne) ClearDescription() *DevicePackageUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the DevicePackageMutation object of the builder.
func (_u *DevicePackageUpdateOne) Mutation() *DevicePackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the DevicePackageUpdate builder.
func (_u *DevicePackageUpdateOne) Where(ps ...predicate.DevicePackage) *DevicePackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DevicePackageUpdateOne) Select(field string, fields ...string) *DevicePackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DevicePackage entity.
func (_u *DevicePackageUpdateOne) Save(ctx context.Context) (*DevicePackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DevicePackageUpdateOne) SaveX(ctx context.Context) *DevicePackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DevicePackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DevicePackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DevicePackageUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := devicepackage.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := devicepackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentVersion(); ok {
		if err := devicepackage.CurrentVersionValidator(v); err != nil {
			return &ValidationError{Name: "current_version", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.current_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvailableVersion(); ok {
		if err := devicepackage.AvailableVersionValidator(v); err != nil {
			return &ValidationError{Name: "available_version", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.available_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackageManager(); ok {
		if err := devicepackage.PackageManagerValidator(v); err != nil {
			return &ValidationError{Name: "package_manager", err: fmt.Errorf(`ent: validator failed for field "DevicePackage.package_manager": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DevicePackageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DevicePackageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DevicePackageUpdateOne) sqlSave(ctx context.Context) (_node *DevicePackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicepackage.Table, devicepackage.Columns, sqlgraph.NewFieldSpec(devicepackage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DevicePackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicepackage.FieldID)
		for _, f := range fields {
			if !devicepackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != devicepackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(devicepackage.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(devicepackage.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(devicepackage.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(devicepackage.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(devicepackage.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(devicepackage.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(devicepackage.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(devicepackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentVersion(); ok {
		_spec.SetField(devicepackage.FieldCurrentVersion, field.TypeString, value)
	}
	if _u.mutation.CurrentVersionCleared() {
		_spec.ClearField(devicepackage.FieldCurrentVersion, field.TypeString)
	}
	if value, ok := _u.mutation.AvailableVersion(); ok {
		_spec.SetField(devicepackage.FieldAvailableVersion, field.TypeString, value)
	}
	if _u.mutation.AvailableVersionCleared() {
		_spec.ClearField(devicepackage.FieldAvailableVersion, field.TypeString)
	}
	if value, ok := _u.mutation.NeedsUpdate(); ok {
		_spec.SetField(devicepackage.FieldNeedsUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSecurityUpdate(); ok {
		_spec.SetField(devicepackage.FieldIsSecurityUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PackageManager(); ok {
		_spec.SetField(devicepackage.FieldPackageManager, field.TypeString, value)
	}
	if _u.mutation.PackageManagerCleared() {
		_spec.ClearField(devicepackage.FieldPackageManager, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(devicepackage.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(devicepackage.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DevicePackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
