// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterface"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterfacelink"
)

// DeviceInterfaceLinkCreate is the builder for creating a DeviceInterfaceLink entity.
type DeviceInterfaceLinkCreate struct {
	config
	mutation *DeviceInterfaceLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (_c *DeviceInterfaceLinkCreate) SetCreateTime(v time.Time) *DeviceInterfaceLinkCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableCreateTime(v *time.Time) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *DeviceInterfaceLinkCreate) SetUpdateTime(v time.Time) *DeviceInterfaceLinkCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *DeviceInterfaceLinkCreate) SetDeleteTime(v time.Time) *DeviceInterfaceLinkCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetInterfaceID sets the "interface_id" field.
func (_c *DeviceInterfaceLinkCreate) SetInterfaceID(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetInterfaceID(v)
	return _c
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (_c *DeviceInterfaceLinkCreate) SetRemoteDeviceID(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetRemoteDeviceID(v)
	return _c
}

// SetNillableRemoteDeviceID sets the "remote_device_id" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableRemoteDeviceID(v *string) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetRemoteDeviceID(*v)
	}
	return _c
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (_c *DeviceInterfaceLinkCreate) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetRemoteInterfaceID(v)
	return _c
}

// SetNillableRemoteInterfaceID sets the "remote_interface_id" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableRemoteInterfaceID(v *string) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetRemoteInterfaceID(*v)
	}
	return _c
}

// SetRemotePortName sets the "remote_port_name" field.
func (_c *DeviceInterfaceLinkCreate) SetRemotePortName(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetRemotePortName(v)
	return _c
}

// SetNillableRemotePortName sets the "remote_port_name" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableRemotePortName(v *string) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetRemotePortName(*v)
	}
	return _c
}

// SetLinkSource sets the "link_source" field.
func (_c *DeviceInterfaceLinkCreate) SetLinkSource(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetLinkSource(v)
	return _c
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableLinkSource(v *string) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetLinkSource(*v)
	}
	return _c
}

// SetLinkVlan sets the "link_vlan" field.
func (_c *DeviceInterfaceLinkCreate) SetLinkVlan(v int32) *DeviceInterfaceLinkCreate {
	_c.mutation.SetLinkVlan(v)
	return _c
}

// SetNillableLinkVlan sets the "link_vlan" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableLinkVlan(v *int32) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetLinkVlan(*v)
	}
	return _c
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (_c *DeviceInterfaceLinkCreate) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkCreate {
	_c.mutation.SetLinkLastSeen(v)
	return _c
}

// SetNillableLinkLastSeen sets the "link_last_seen" field if the given value is not nil.
func (_c *DeviceInterfaceLinkCreate) SetNillableLinkLastSeen(v *time.Time) *DeviceInterfaceLinkCreate {
	if v != nil {
		_c.SetLinkLastSeen(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceInterfaceLinkCreate) SetID(v string) *DeviceInterfaceLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetInterface sets the "interface" edge to the DeviceInterface entity.
func (_c *DeviceInterfaceLinkCreate) SetInterface(v *DeviceInterface) *DeviceInterfaceLinkCreate {
	return _c.SetInterfaceID(v.ID)
}

// Mutation returns the DeviceInterfaceLinkMutation object of the builder.
func (_c *DeviceInterfaceLinkCreate) Mutation() *DeviceInterfaceLinkMutation {
	return _c.mutation
}

// Save creates the DeviceInterfaceLink in the database.
func (_c *DeviceInterfaceLinkCreate) Save(ctx context.Context) (*DeviceInterfaceLink, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceInterfaceLinkCreate) SaveX(ctx context.Context) *DeviceInterfaceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceInterfaceLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceInterfaceLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceInterfaceLinkCreate) check() error {
	if _, ok := _c.mutation.InterfaceID(); !ok {
		return &ValidationError{Name: "interface_id", err: errors.New(`ent: missing required field "DeviceInterfaceLink.interface_id"`)}
	}
	if v, ok := _c.mutation.InterfaceID(); ok {
		if err := deviceinterfacelink.InterfaceIDValidator(v); err != nil {
			return &ValidationError{Name: "interface_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterfaceLink.interface_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := deviceinterfacelink.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterfaceLink.id": %w`, err)}
		}
	}
	if len(_c.mutation.InterfaceIDs()) == 0 {
		return &ValidationError{Name: "interface", err: errors.New(`ent: missing required edge "DeviceInterfaceLink.interface"`)}
	}
	return nil
}

func (_c *DeviceInterfaceLinkCreate) sqlSave(ctx context.Context) (*DeviceInterfaceLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected DeviceInterfaceLink.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceInterfaceLinkCreate) createSpec() (*DeviceInterfaceLink, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceInterfaceLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deviceinterfacelink.Table, sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.RemoteDeviceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteDeviceID, field.TypeString, value)
		_node.RemoteDeviceID = value
	}
	if value, ok := _c.mutation.RemoteInterfaceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteInterfaceID, field.TypeString, value)
		_node.RemoteInterfaceID = value
	}
	if value, ok := _c.mutation.RemotePortName(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemotePortName, field.TypeString, value)
		_node.RemotePortName = value
	}
	if value, ok := _c.mutation.LinkSource(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkSource, field.TypeString, value)
		_node.LinkSource = value
	}
	if value, ok := _c.mutation.LinkVlan(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32, value)
		_node.LinkVlan = &value
	}
	if value, ok := _c.mutation.LinkLastSeen(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkLastSeen, field.TypeTime, value)
		_node.LinkLastSeen = &value
	}
	if nodes := _c.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterfacelink.InterfaceTable,
			Columns: []string{deviceinterfacelink.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InterfaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceInterfaceLink.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceInterfaceLinkUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceInterfaceLinkCreate) OnConflict(opts ...sql.ConflictOption) *DeviceInterfaceLinkUpsertOne {
	_c.conflict = opts
	return &DeviceInterfaceLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceInterfaceLinkCreate) OnConflictColumns(columns ...string) *DeviceInterfaceLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceInterfaceLinkUpsertOne{
		create: _c,
	}
}

type (
	// DeviceInterfaceLinkUpsertOne is the builder for "upsert"-ing
	//  one DeviceInterfaceLink node.
	DeviceInterfaceLinkUpsertOne struct {
		create *DeviceInterfaceLinkCreate
	}

	// DeviceInterfaceLinkUpsert is the "OnConflict" setter.
	DeviceInterfaceLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceLinkUpsert) SetUpdateTime(v time.Time) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateUpdateTime() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceLinkUpsert) ClearUpdateTime() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceLinkUpsert) SetDeleteTime(v time.Time) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateDeleteTime() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceLinkUpsert) ClearDeleteTime() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldDeleteTime)
	return u
}

// SetInterfaceID sets the "interface_id" field.
func (u *DeviceInterfaceLinkUpsert) SetInterfaceID(v string) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldInterfaceID, v)
	return u
}

// UpdateInterfaceID sets the "interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateInterfaceID() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldInterfaceID)
	return u
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsert) SetRemoteDeviceID(v string) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldRemoteDeviceID, v)
	return u
}

// UpdateRemoteDeviceID sets the "remote_device_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateRemoteDeviceID() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldRemoteDeviceID)
	return u
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsert) ClearRemoteDeviceID() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldRemoteDeviceID)
	return u
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsert) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldRemoteInterfaceID, v)
	return u
}

// UpdateRemoteInterfaceID sets the "remote_interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateRemoteInterfaceID() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldRemoteInterfaceID)
	return u
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsert) ClearRemoteInterfaceID() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldRemoteInterfaceID)
	return u
}

// SetRemotePortName sets the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsert) SetRemotePortName(v string) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldRemotePortName, v)
	return u
}

// UpdateRemotePortName sets the "remote_port_name" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateRemotePortName() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldRemotePortName)
	return u
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsert) ClearRemotePortName() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldRemotePortName)
	return u
}

// SetLinkSource sets the "link_source" field.
func (u *DeviceInterfaceLinkUpsert) SetLinkSource(v string) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldLinkSource, v)
	return u
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateLinkSource() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldLinkSource)
	return u
}

// ClearLinkSource clears the value of the "link_source" field.
func (u *DeviceInterfaceLinkUpsert) ClearLinkSource() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldLinkSource)
	return u
}

// SetLinkVlan sets the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsert) SetLinkVlan(v int32) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldLinkVlan, v)
	return u
}

// UpdateLinkVlan sets the "link_vlan" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateLinkVlan() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldLinkVlan)
	return u
}

// AddLinkVlan adds v to the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsert) AddLinkVlan(v int32) *DeviceInterfaceLinkUpsert {
	u.Add(deviceinterfacelink.FieldLinkVlan, v)
	return u
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsert) ClearLinkVlan() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldLinkVlan)
	return u
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsert) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkUpsert {
	u.Set(deviceinterfacelink.FieldLinkLastSeen, v)
	return u
}

// UpdateLinkLastSeen sets the "link_last_seen" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsert) UpdateLinkLastSeen() *DeviceInterfaceLinkUpsert {
	u.SetExcluded(deviceinterfacelink.FieldLinkLastSeen)
	return u
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsert) ClearLinkLastSeen() *DeviceInterfaceLinkUpsert {
	u.SetNull(deviceinterfacelink.FieldLinkLastSeen)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deviceinterfacelink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceInterfaceLinkUpsertOne) UpdateNewValues() *DeviceInterfaceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deviceinterfacelink.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(deviceinterfacelink.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeviceInterfaceLinkUpsertOne) Ignore() *DeviceInterfaceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceInterfaceLinkUpsertOne) DoNothing() *DeviceInterfaceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceInterfaceLinkCreate.OnConflict
// documentation for more info.
func (u *DeviceInterfaceLinkUpsertOne) Update(set func(*DeviceInterfaceLinkUpsert)) *DeviceInterfaceLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceInterfaceLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceLinkUpsertOne) SetUpdateTime(v time.Time) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateUpdateTime() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearUpdateTime() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceLinkUpsertOne) SetDeleteTime(v time.Time) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateDeleteTime() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearDeleteTime() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearDeleteTime()
	})
}

// SetInterfaceID sets the "interface_id" field.
func (u *DeviceInterfaceLinkUpsertOne) SetInterfaceID(v string) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetInterfaceID(v)
	})
}

// UpdateInterfaceID sets the "interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateInterfaceID() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateInterfaceID()
	})
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsertOne) SetRemoteDeviceID(v string) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemoteDeviceID(v)
	})
}

// UpdateRemoteDeviceID sets the "remote_device_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateRemoteDeviceID() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemoteDeviceID()
	})
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearRemoteDeviceID() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemoteDeviceID()
	})
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsertOne) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemoteInterfaceID(v)
	})
}

// UpdateRemoteInterfaceID sets the "remote_interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateRemoteInterfaceID() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemoteInterfaceID()
	})
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearRemoteInterfaceID() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemoteInterfaceID()
	})
}

// SetRemotePortName sets the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsertOne) SetRemotePortName(v string) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemotePortName(v)
	})
}

// UpdateRemotePortName sets the "remote_port_name" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateRemotePortName() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemotePortName()
	})
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearRemotePortName() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemotePortName()
	})
}

// SetLinkSource sets the "link_source" field.
func (u *DeviceInterfaceLinkUpsertOne) SetLinkSource(v string) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkSource(v)
	})
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateLinkSource() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkSource()
	})
}

// ClearLinkSource clears the value of the "link_source" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearLinkSource() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkSource()
	})
}

// SetLinkVlan sets the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertOne) SetLinkVlan(v int32) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkVlan(v)
	})
}

// AddLinkVlan adds v to the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertOne) AddLinkVlan(v int32) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.AddLinkVlan(v)
	})
}

// UpdateLinkVlan sets the "link_vlan" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateLinkVlan() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkVlan()
	})
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearLinkVlan() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkVlan()
	})
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsertOne) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkLastSeen(v)
	})
}

// UpdateLinkLastSeen sets the "link_last_seen" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertOne) UpdateLinkLastSeen() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkLastSeen()
	})
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsertOne) ClearLinkLastSeen() *DeviceInterfaceLinkUpsertOne {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkLastSeen()
	})
}

// Exec executes the query.
func (u *DeviceInterfaceLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceInterfaceLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceInterfaceLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeviceInterfaceLinkUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeviceInterfaceLinkUpsertOne.ID is not supported by MySQL driver. Use DeviceInterfaceLinkUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeviceInterfaceLinkUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeviceInterfaceLinkCreateBulk is the builder for creating many DeviceInterfaceLink entities in bulk.
type DeviceInterfaceLinkCreateBulk struct {
	config
	err      error
	builders []*DeviceInterfaceLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the DeviceInterfaceLink entities in the database.
func (_c *DeviceInterfaceLinkCreateBulk) Save(ctx context.Context) ([]*DeviceInterfaceLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeviceInterfaceLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceInterfaceLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceInterfaceLinkCreateBulk) SaveX(ctx context.Context) []*DeviceInterfaceLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceInterfaceLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceInterfaceLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeviceInterfaceLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeviceInterfaceLinkUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *DeviceInterfaceLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeviceInterfaceLinkUpsertBulk {
	_c.conflict = opts
	return &DeviceInterfaceLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeviceInterfaceLinkCreateBulk) OnConflictColumns(columns ...string) *DeviceInterfaceLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeviceInterfaceLinkUpsertBulk{
		create: _c,
	}
}

// DeviceInterfaceLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of DeviceInterfaceLink nodes.
type DeviceInterfaceLinkUpsertBulk struct {
	create *DeviceInterfaceLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deviceinterfacelink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeviceInterfaceLinkUpsertBulk) UpdateNewValues() *DeviceInterfaceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deviceinterfacelink.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(deviceinterfacelink.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeviceInterfaceLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeviceInterfaceLinkUpsertBulk) Ignore() *DeviceInterfaceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeviceInterfaceLinkUpsertBulk) DoNothing() *DeviceInterfaceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeviceInterfaceLinkCreateBulk.OnConflict
// documentation for more info.
func (u *DeviceInterfaceLinkUpsertBulk) Update(set func(*DeviceInterfaceLinkUpsert)) *DeviceInterfaceLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeviceInterfaceLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetUpdateTime(v time.Time) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateUpdateTime() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearUpdateTime() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetDeleteTime(v time.Time) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateDeleteTime() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearDeleteTime() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearDeleteTime()
	})
}

// SetInterfaceID sets the "interface_id" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetInterfaceID(v string) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetInterfaceID(v)
	})
}

// UpdateInterfaceID sets the "interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateInterfaceID() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateInterfaceID()
	})
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetRemoteDeviceID(v string) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemoteDeviceID(v)
	})
}

// UpdateRemoteDeviceID sets the "remote_device_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateRemoteDeviceID() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemoteDeviceID()
	})
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearRemoteDeviceID() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemoteDeviceID()
	})
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemoteInterfaceID(v)
	})
}

// UpdateRemoteInterfaceID sets the "remote_interface_id" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateRemoteInterfaceID() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemoteInterfaceID()
	})
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearRemoteInterfaceID() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemoteInterfaceID()
	})
}

// SetRemotePortName sets the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetRemotePortName(v string) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetRemotePortName(v)
	})
}

// UpdateRemotePortName sets the "remote_port_name" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateRemotePortName() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateRemotePortName()
	})
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearRemotePortName() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearRemotePortName()
	})
}

// SetLinkSource sets the "link_source" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetLinkSource(v string) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkSource(v)
	})
}

// UpdateLinkSource sets the "link_source" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateLinkSource() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkSource()
	})
}

// ClearLinkSource clears the value of the "link_source" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearLinkSource() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkSource()
	})
}

// SetLinkVlan sets the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetLinkVlan(v int32) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkVlan(v)
	})
}

// AddLinkVlan adds v to the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertBulk) AddLinkVlan(v int32) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.AddLinkVlan(v)
	})
}

// UpdateLinkVlan sets the "link_vlan" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateLinkVlan() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkVlan()
	})
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearLinkVlan() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkVlan()
	})
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsertBulk) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.SetLinkLastSeen(v)
	})
}

// UpdateLinkLastSeen sets the "link_last_seen" field to the value that was provided on create.
func (u *DeviceInterfaceLinkUpsertBulk) UpdateLinkLastSeen() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.UpdateLinkLastSeen()
	})
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (u *DeviceInterfaceLinkUpsertBulk) ClearLinkLastSeen() *DeviceInterfaceLinkUpsertBulk {
	return u.Update(func(s *DeviceInterfaceLinkUpsert) {
		s.ClearLinkLastSeen()
	})
}

// Exec executes the query.
func (u *DeviceInterfaceLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeviceInterfaceLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeviceInterfaceLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeviceInterfaceLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
