// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/devicepackage"
)

// DevicePackage is the model entity for the DevicePackage schema.
type DevicePackage struct {
	config `json:"-"`
	// ID of the ent.
	// Unique identifier
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Device ID
	DeviceID string `json:"device_id,omitempty"`
	// Package name
	Name string `json:"name,omitempty"`
	// Currently installed version
	CurrentVersion string `json:"current_version,omitempty"`
	// Available version for update
	AvailableVersion string `json:"available_version,omitempty"`
	// Whether the package has an update available
	NeedsUpdate bool `json:"needs_update,omitempty"`
	// Whether the available update is a security update
	IsSecurityUpdate bool `json:"is_security_update,omitempty"`
	// Package manager: apt, dnf, apk, pacman
	PackageManager string `json:"package_manager,omitempty"`
	// Package description
	Description  string `json:"description,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DevicePackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicepackage.FieldNeedsUpdate, devicepackage.FieldIsSecurityUpdate:
			values[i] = new(sql.NullBool)
		case devicepackage.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case devicepackage.FieldID, devicepackage.FieldDeviceID, devicepackage.FieldName, devicepackage.FieldCurrentVersion, devicepackage.FieldAvailableVersion, devicepackage.FieldPackageManager, devicepackage.FieldDescription:
			values[i] = new(sql.NullString)
		case devicepackage.FieldCreateTime, devicepackage.FieldUpdateTime, devicepackage.FieldDeleteTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DevicePackage fields.
func (_m *DevicePackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicepackage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case devicepackage.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case devicepackage.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case devicepackage.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case devicepackage.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case devicepackage.FieldDeviceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.String
			}
		case devicepackage.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case devicepackage.FieldCurrentVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_version", values[i])
			} else if value.Valid {
				_m.CurrentVersion = value.String
			}
		case devicepackage.FieldAvailableVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field available_version", values[i])
			} else if value.Valid {
				_m.AvailableVersion = value.String
			}
		case devicepackage.FieldNeedsUpdate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field needs_update", values[i])
			} else if value.Valid {
				_m.NeedsUpdate = value.Bool
			}
		case devicepackage.FieldIsSecurityUpdate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_security_update", values[i])
			} else if value.Valid {
				_m.IsSecurityUpdate = value.Bool
			}
		case devicepackage.FieldPackageManager:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_manager", values[i])
			} else if value.Valid {
				_m.PackageManager = value.String
			}
		case devicepackage.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DevicePackage.
// This includes values selected through modifiers, order, etc.
func (_m *DevicePackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DevicePackage.
// Note that you need to call DevicePackage.Unwrap() before calling this method if this DevicePackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DevicePackage) Update() *DevicePackageUpdateOne {
	return NewDevicePackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DevicePackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DevicePackage) Unwrap() *DevicePackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DevicePackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DevicePackage) String() string {
	var builder strings.Builder
	builder.WriteString("DevicePackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(_m.DeviceID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("current_version=")
	builder.WriteString(_m.CurrentVersion)
	builder.WriteString(", ")
	builder.WriteString("available_version=")
	builder.WriteString(_m.AvailableVersion)
	builder.WriteString(", ")
	builder.WriteString("needs_update=")
	builder.WriteString(fmt.Sprintf("%v", _m.NeedsUpdate))
	builder.WriteString(", ")
	builder.WriteString("is_security_update=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSecurityUpdate))
	builder.WriteString(", ")
	builder.WriteString("package_manager=")
	builder.WriteString(_m.PackageManager)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// DevicePackages is a parsable slice of DevicePackage.
type DevicePackages []*DevicePackage
