// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/device"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterface"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterfacelink"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// DeviceInterfaceUpdate is the builder for updating DeviceInterface entities.
type DeviceInterfaceUpdate struct {
	config
	hooks     []Hook
	mutation  *DeviceInterfaceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeviceInterfaceUpdate builder.
func (_u *DeviceInterfaceUpdate) Where(ps ...predicate.DeviceInterface) *DeviceInterfaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeviceInterfaceUpdate) SetUpdateTime(v time.Time) *DeviceInterfaceUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeviceInterfaceUpdate) ClearUpdateTime() *DeviceInterfaceUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeviceInterfaceUpdate) SetDeleteTime(v time.Time) *DeviceInterfaceUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeviceInterfaceUpdate) ClearDeleteTime() *DeviceInterfaceUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceInterfaceUpdate) SetDeviceID(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableDeviceID(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceInterfaceUpdate) SetName(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableName(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMACAddress sets the "mac_address" field.
func (_u *DeviceInterfaceUpdate) SetMACAddress(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetMACAddress(v)
	return _u
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableMACAddress(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetMACAddress(*v)
	}
	return _u
}

// ClearMACAddress clears the value of the "mac_address" field.
func (_u *DeviceInterfaceUpdate) ClearMACAddress() *DeviceInterfaceUpdate {
	_u.mutation.ClearMACAddress()
	return _u
}

// SetInterfaceType sets the "interface_type" field.
func (_u *DeviceInterfaceUpdate) SetInterfaceType(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetInterfaceType(v)
	return _u
}

// SetNillableInterfaceType sets the "interface_type" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableInterfaceType(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetInterfaceType(*v)
	}
	return _u
}

// ClearInterfaceType clears the value of the "interface_type" field.
func (_u *DeviceInterfaceUpdate) ClearInterfaceType() *DeviceInterfaceUpdate {
	_u.mutation.ClearInterfaceType()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DeviceInterfaceUpdate) SetEnabled(v bool) *DeviceInterfaceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableEnabled(v *bool) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSpeedMbps sets the "speed_mbps" field.
func (_u *DeviceInterfaceUpdate) SetSpeedMbps(v int32) *DeviceInterfaceUpdate {
	_u.mutation.ResetSpeedMbps()
	_u.mutation.SetSpeedMbps(v)
	return _u
}

// SetNillableSpeedMbps sets the "speed_mbps" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableSpeedMbps(v *int32) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetSpeedMbps(*v)
	}
	return _u
}

// AddSpeedMbps adds value to the "speed_mbps" field.
func (_u *DeviceInterfaceUpdate) AddSpeedMbps(v int32) *DeviceInterfaceUpdate {
	_u.mutation.AddSpeedMbps(v)
	return _u
}

// ClearSpeedMbps clears the value of the "speed_mbps" field.
func (_u *DeviceInterfaceUpdate) ClearSpeedMbps() *DeviceInterfaceUpdate {
	_u.mutation.ClearSpeedMbps()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DeviceInterfaceUpdate) SetDescription(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableDescription(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DeviceInterfaceUpdate) ClearDescription() *DeviceInterfaceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIfIndex sets the "if_index" field.
func (_u *DeviceInterfaceUpdate) SetIfIndex(v int32) *DeviceInterfaceUpdate {
	_u.mutation.ResetIfIndex()
	_u.mutation.SetIfIndex(v)
	return _u
}

// SetNillableIfIndex sets the "if_index" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableIfIndex(v *int32) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetIfIndex(*v)
	}
	return _u
}

// AddIfIndex adds value to the "if_index" field.
func (_u *DeviceInterfaceUpdate) AddIfIndex(v int32) *DeviceInterfaceUpdate {
	_u.mutation.AddIfIndex(v)
	return _u
}

// ClearIfIndex clears the value of the "if_index" field.
func (_u *DeviceInterfaceUpdate) ClearIfIndex() *DeviceInterfaceUpdate {
	_u.mutation.ClearIfIndex()
	return _u
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (_u *DeviceInterfaceUpdate) SetRemoteDeviceID(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetRemoteDeviceID(v)
	return _u
}

// SetNillableRemoteDeviceID sets the "remote_device_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableRemoteDeviceID(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetRemoteDeviceID(*v)
	}
	return _u
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (_u *DeviceInterfaceUpdate) ClearRemoteDeviceID() *DeviceInterfaceUpdate {
	_u.mutation.ClearRemoteDeviceID()
	return _u
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (_u *DeviceInterfaceUpdate) SetRemoteInterfaceID(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetRemoteInterfaceID(v)
	return _u
}

// SetNillableRemoteInterfaceID sets the "remote_interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableRemoteInterfaceID(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetRemoteInterfaceID(*v)
	}
	return _u
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (_u *DeviceInterfaceUpdate) ClearRemoteInterfaceID() *DeviceInterfaceUpdate {
	_u.mutation.ClearRemoteInterfaceID()
	return _u
}

// SetRemotePortName sets the "remote_port_name" field.
func (_u *DeviceInterfaceUpdate) SetRemotePortName(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetRemotePortName(v)
	return _u
}

// SetNillableRemotePortName sets the "remote_port_name" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableRemotePortName(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetRemotePortName(*v)
	}
	return _u
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (_u *DeviceInterfaceUpdate) ClearRemotePortName() *DeviceInterfaceUpdate {
	_u.mutation.ClearRemotePortName()
	return _u
}

// SetLinkSource sets the "link_source" field.
func (_u *DeviceInterfaceUpdate) SetLinkSource(v string) *DeviceInterfaceUpdate {
	_u.mutation.SetLinkSource(v)
	return _u
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableLinkSource(v *string) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetLinkSource(*v)
	}
	return _u
}

// ClearLinkSource clears the value of the "link_source" field.
func (_u *DeviceInterfaceUpdate) ClearLinkSource() *DeviceInterfaceUpdate {
	_u.mutation.ClearLinkSource()
	return _u
}

// SetLinkVlan sets the "link_vlan" field.
func (_u *DeviceInterfaceUpdate) SetLinkVlan(v int32) *DeviceInterfaceUpdate {
	_u.mutation.ResetLinkVlan()
	_u.mutation.SetLinkVlan(v)
	return _u
}

// SetNillableLinkVlan sets the "link_vlan" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableLinkVlan(v *int32) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetLinkVlan(*v)
	}
	return _u
}

// AddLinkVlan adds value to the "link_vlan" field.
func (_u *DeviceInterfaceUpdate) AddLinkVlan(v int32) *DeviceInterfaceUpdate {
	_u.mutation.AddLinkVlan(v)
	return _u
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (_u *DeviceInterfaceUpdate) ClearLinkVlan() *DeviceInterfaceUpdate {
	_u.mutation.ClearLinkVlan()
	return _u
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (_u *DeviceInterfaceUpdate) SetLinkLastSeen(v time.Time) *DeviceInterfaceUpdate {
	_u.mutation.SetLinkLastSeen(v)
	return _u
}

// SetNillableLinkLastSeen sets the "link_last_seen" field if the given value is not nil.
func (_u *DeviceInterfaceUpdate) SetNillableLinkLastSeen(v *time.Time) *DeviceInterfaceUpdate {
	if v != nil {
		_u.SetLinkLastSeen(*v)
	}
	return _u
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (_u *DeviceInterfaceUpdate) ClearLinkLastSeen() *DeviceInterfaceUpdate {
	_u.mutation.ClearLinkLastSeen()
	return _u
}

// SetDevice sets the "device" edge to the Device entity.
func (_u *DeviceInterfaceUpdate) SetDevice(v *Device) *DeviceInterfaceUpdate {
	return _u.SetDeviceID(v.ID)
}

// AddLinkIDs adds the "links" edge to the DeviceInterfaceLink entity by IDs.
func (_u *DeviceInterfaceUpdate) AddLinkIDs(ids ...string) *DeviceInterfaceUpdate {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the DeviceInterfaceLink entity.
func (_u *DeviceInterfaceUpdate) AddLinks(v ...*DeviceInterfaceLink) *DeviceInterfaceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// Mutation returns the DeviceInterfaceMutation object of the builder.
func (_u *DeviceInterfaceUpdate) Mutation() *DeviceInterfaceMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the Device entity.
func (_u *DeviceInterfaceUpdate) ClearDevice() *DeviceInterfaceUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// ClearLinks clears all "links" edges to the DeviceInterfaceLink entity.
func (_u *DeviceInterfaceUpdate) ClearLinks() *DeviceInterfaceUpdate {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to DeviceInterfaceLink entities by IDs.
func (_u *DeviceInterfaceUpdate) RemoveLinkIDs(ids ...string) *DeviceInterfaceUpdate {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to DeviceInterfaceLink entities.
func (_u *DeviceInterfaceUpdate) RemoveLinks(v ...*DeviceInterfaceLink) *DeviceInterfaceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceInterfaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceInterfaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceInterfaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceInterfaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceInterfaceUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := deviceinterface.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := deviceinterface.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.name": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceInterface.device"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceInterfaceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceInterfaceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceInterfaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deviceinterface.Table, deviceinterface.Columns, sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deviceinterface.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterface.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deviceinterface.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterface.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deviceinterface.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deviceinterface.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MACAddress(); ok {
		_spec.SetField(deviceinterface.FieldMACAddress, field.TypeString, value)
	}
	if _u.mutation.MACAddressCleared() {
		_spec.ClearField(deviceinterface.FieldMACAddress, field.TypeString)
	}
	if value, ok := _u.mutation.InterfaceType(); ok {
		_spec.SetField(deviceinterface.FieldInterfaceType, field.TypeString, value)
	}
	if _u.mutation.InterfaceTypeCleared() {
		_spec.ClearField(deviceinterface.FieldInterfaceType, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(deviceinterface.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SpeedMbps(); ok {
		_spec.SetField(deviceinterface.FieldSpeedMbps, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSpeedMbps(); ok {
		_spec.AddField(deviceinterface.FieldSpeedMbps, field.TypeInt32, value)
	}
	if _u.mutation.SpeedMbpsCleared() {
		_spec.ClearField(deviceinterface.FieldSpeedMbps, field.TypeInt32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(deviceinterface.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(deviceinterface.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IfIndex(); ok {
		_spec.SetField(deviceinterface.FieldIfIndex, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIfIndex(); ok {
		_spec.AddField(deviceinterface.FieldIfIndex, field.TypeInt32, value)
	}
	if _u.mutation.IfIndexCleared() {
		_spec.ClearField(deviceinterface.FieldIfIndex, field.TypeInt32)
	}
	if value, ok := _u.mutation.RemoteDeviceID(); ok {
		_spec.SetField(deviceinterface.FieldRemoteDeviceID, field.TypeString, value)
	}
	if _u.mutation.RemoteDeviceIDCleared() {
		_spec.ClearField(deviceinterface.FieldRemoteDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteInterfaceID(); ok {
		_spec.SetField(deviceinterface.FieldRemoteInterfaceID, field.TypeString, value)
	}
	if _u.mutation.RemoteInterfaceIDCleared() {
		_spec.ClearField(deviceinterface.FieldRemoteInterfaceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemotePortName(); ok {
		_spec.SetField(deviceinterface.FieldRemotePortName, field.TypeString, value)
	}
	if _u.mutation.RemotePortNameCleared() {
		_spec.ClearField(deviceinterface.FieldRemotePortName, field.TypeString)
	}
	if value, ok := _u.mutation.LinkSource(); ok {
		_spec.SetField(deviceinterface.FieldLinkSource, field.TypeString, value)
	}
	if _u.mutation.LinkSourceCleared() {
		_spec.ClearField(deviceinterface.FieldLinkSource, field.TypeString)
	}
	if value, ok := _u.mutation.LinkVlan(); ok {
		_spec.SetField(deviceinterface.FieldLinkVlan, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLinkVlan(); ok {
		_spec.AddField(deviceinterface.FieldLinkVlan, field.TypeInt32, value)
	}
	if _u.mutation.LinkVlanCleared() {
		_spec.ClearField(deviceinterface.FieldLinkVlan, field.TypeInt32)
	}
	if value, ok := _u.mutation.LinkLastSeen(); ok {
		_spec.SetField(deviceinterface.FieldLinkLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LinkLastSeenCleared() {
		_spec.ClearField(deviceinterface.FieldLinkLastSeen, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterface.DeviceTable,
			Columns: []string{deviceinterface.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterface.DeviceTable,
			Columns: []string{deviceinterface.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinterface.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceInterfaceUpdateOne is the builder for updating a single DeviceInterface entity.
type DeviceInterfaceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeviceInterfaceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeviceInterfaceUpdateOne) SetUpdateTime(v time.Time) *DeviceInterfaceUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeviceInterfaceUpdateOne) ClearUpdateTime() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeviceInterfaceUpdateOne) SetDeleteTime(v time.Time) *DeviceInterfaceUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeviceInterfaceUpdateOne) ClearDeleteTime() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceInterfaceUpdateOne) SetDeviceID(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableDeviceID(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceInterfaceUpdateOne) SetName(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableName(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMACAddress sets the "mac_address" field.
func (_u *DeviceInterfaceUpdateOne) SetMACAddress(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetMACAddress(v)
	return _u
}

// SetNillableMACAddress sets the "mac_address" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableMACAddress(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetMACAddress(*v)
	}
	return _u
}

// ClearMACAddress clears the value of the "mac_address" field.
func (_u *DeviceInterfaceUpdateOne) ClearMACAddress() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearMACAddress()
	return _u
}

// SetInterfaceType sets the "interface_type" field.
func (_u *DeviceInterfaceUpdateOne) SetInterfaceType(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetInterfaceType(v)
	return _u
}

// SetNillableInterfaceType sets the "interface_type" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableInterfaceType(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetInterfaceType(*v)
	}
	return _u
}

// ClearInterfaceType clears the value of the "interface_type" field.
func (_u *DeviceInterfaceUpdateOne) ClearInterfaceType() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearInterfaceType()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DeviceInterfaceUpdateOne) SetEnabled(v bool) *DeviceInterfaceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableEnabled(v *bool) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSpeedMbps sets the "speed_mbps" field.
func (_u *DeviceInterfaceUpdateOne) SetSpeedMbps(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.ResetSpeedMbps()
	_u.mutation.SetSpeedMbps(v)
	return _u
}

// SetNillableSpeedMbps sets the "speed_mbps" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableSpeedMbps(v *int32) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetSpeedMbps(*v)
	}
	return _u
}

// AddSpeedMbps adds value to the "speed_mbps" field.
func (_u *DeviceInterfaceUpdateOne) AddSpeedMbps(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.AddSpeedMbps(v)
	return _u
}

// ClearSpeedMbps clears the value of the "speed_mbps" field.
func (_u *DeviceInterfaceUpdateOne) ClearSpeedMbps() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearSpeedMbps()
	return _u
}

// SetDescription sets the "description" field.
func (_u *DeviceInterfaceUpdateOne) SetDescription(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableDescription(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DeviceInterfaceUpdateOne) ClearDescription() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIfIndex sets the "if_index" field.
func (_u *DeviceInterfaceUpdateOne) SetIfIndex(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.ResetIfIndex()
	_u.mutation.SetIfIndex(v)
	return _u
}

// SetNillableIfIndex sets the "if_index" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableIfIndex(v *int32) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetIfIndex(*v)
	}
	return _u
}

// AddIfIndex adds value to the "if_index" field.
func (_u *DeviceInterfaceUpdateOne) AddIfIndex(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.AddIfIndex(v)
	return _u
}

// ClearIfIndex clears the value of the "if_index" field.
func (_u *DeviceInterfaceUpdateOne) ClearIfIndex() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearIfIndex()
	return _u
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (_u *DeviceInterfaceUpdateOne) SetRemoteDeviceID(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetRemoteDeviceID(v)
	return _u
}

// SetNillableRemoteDeviceID sets the "remote_device_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableRemoteDeviceID(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetRemoteDeviceID(*v)
	}
	return _u
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (_u *DeviceInterfaceUpdateOne) ClearRemoteDeviceID() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearRemoteDeviceID()
	return _u
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (_u *DeviceInterfaceUpdateOne) SetRemoteInterfaceID(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetRemoteInterfaceID(v)
	return _u
}

// SetNillableRemoteInterfaceID sets the "remote_interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableRemoteInterfaceID(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetRemoteInterfaceID(*v)
	}
	return _u
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (_u *DeviceInterfaceUpdateOne) ClearRemoteInterfaceID() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearRemoteInterfaceID()
	return _u
}

// SetRemotePortName sets the "remote_port_name" field.
func (_u *DeviceInterfaceUpdateOne) SetRemotePortName(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetRemotePortName(v)
	return _u
}

// SetNillableRemotePortName sets the "remote_port_name" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableRemotePortName(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetRemotePortName(*v)
	}
	return _u
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (_u *DeviceInterfaceUpdateOne) ClearRemotePortName() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearRemotePortName()
	return _u
}

// SetLinkSource sets the "link_source" field.
func (_u *DeviceInterfaceUpdateOne) SetLinkSource(v string) *DeviceInterfaceUpdateOne {
	_u.mutation.SetLinkSource(v)
	return _u
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableLinkSource(v *string) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetLinkSource(*v)
	}
	return _u
}

// ClearLinkSource clears the value of the "link_source" field.
func (_u *DeviceInterfaceUpdateOne) ClearLinkSource() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearLinkSource()
	return _u
}

// SetLinkVlan sets the "link_vlan" field.
func (_u *DeviceInterfaceUpdateOne) SetLinkVlan(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.ResetLinkVlan()
	_u.mutation.SetLinkVlan(v)
	return _u
}

// SetNillableLinkVlan sets the "link_vlan" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableLinkVlan(v *int32) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetLinkVlan(*v)
	}
	return _u
}

// AddLinkVlan adds value to the "link_vlan" field.
func (_u *DeviceInterfaceUpdateOne) AddLinkVlan(v int32) *DeviceInterfaceUpdateOne {
	_u.mutation.AddLinkVlan(v)
	return _u
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (_u *DeviceInterfaceUpdateOne) ClearLinkVlan() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearLinkVlan()
	return _u
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (_u *DeviceInterfaceUpdateOne) SetLinkLastSeen(v time.Time) *DeviceInterfaceUpdateOne {
	_u.mutation.SetLinkLastSeen(v)
	return _u
}

// SetNillableLinkLastSeen sets the "link_last_seen" field if the given value is not nil.
func (_u *DeviceInterfaceUpdateOne) SetNillableLinkLastSeen(v *time.Time) *DeviceInterfaceUpdateOne {
	if v != nil {
		_u.SetLinkLastSeen(*v)
	}
	return _u
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (_u *DeviceInterfaceUpdateOne) ClearLinkLastSeen() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearLinkLastSeen()
	return _u
}

// SetDevice sets the "device" edge to the Device entity.
func (_u *DeviceInterfaceUpdateOne) SetDevice(v *Device) *DeviceInterfaceUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// AddLinkIDs adds the "links" edge to the DeviceInterfaceLink entity by IDs.
func (_u *DeviceInterfaceUpdateOne) AddLinkIDs(ids ...string) *DeviceInterfaceUpdateOne {
	_u.mutation.AddLinkIDs(ids...)
	return _u
}

// AddLinks adds the "links" edges to the DeviceInterfaceLink entity.
func (_u *DeviceInterfaceUpdateOne) AddLinks(v ...*DeviceInterfaceLink) *DeviceInterfaceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLinkIDs(ids...)
}

// Mutation returns the DeviceInterfaceMutation object of the builder.
func (_u *DeviceInterfaceUpdateOne) Mutation() *DeviceInterfaceMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the Device entity.
func (_u *DeviceInterfaceUpdateOne) ClearDevice() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// ClearLinks clears all "links" edges to the DeviceInterfaceLink entity.
func (_u *DeviceInterfaceUpdateOne) ClearLinks() *DeviceInterfaceUpdateOne {
	_u.mutation.ClearLinks()
	return _u
}

// RemoveLinkIDs removes the "links" edge to DeviceInterfaceLink entities by IDs.
func (_u *DeviceInterfaceUpdateOne) RemoveLinkIDs(ids ...string) *DeviceInterfaceUpdateOne {
	_u.mutation.RemoveLinkIDs(ids...)
	return _u
}

// RemoveLinks removes "links" edges to DeviceInterfaceLink entities.
func (_u *DeviceInterfaceUpdateOne) RemoveLinks(v ...*DeviceInterfaceLink) *DeviceInterfaceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLinkIDs(ids...)
}

// Where appends a list predicates to the DeviceInterfaceUpdate builder.
func (_u *DeviceInterfaceUpdateOne) Where(ps ...predicate.DeviceInterface) *DeviceInterfaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceInterfaceUpdateOne) Select(field string, fields ...string) *DeviceInterfaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeviceInterface entity.
func (_u *DeviceInterfaceUpdateOne) Save(ctx context.Context) (*DeviceInterface, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceInterfaceUpdateOne) SaveX(ctx context.Context) *DeviceInterface {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceInterfaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceInterfaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceInterfaceUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := deviceinterface.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.device_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := deviceinterface.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceInterface.name": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceInterface.device"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceInterfaceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceInterfaceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceInterfaceUpdateOne) sqlSave(ctx context.Context) (_node *DeviceInterface, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deviceinterface.Table, deviceinterface.Columns, sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceInterface.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceinterface.FieldID)
		for _, f := range fields {
			if !deviceinterface.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deviceinterface.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deviceinterface.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterface.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deviceinterface.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterface.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deviceinterface.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deviceinterface.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MACAddress(); ok {
		_spec.SetField(deviceinterface.FieldMACAddress, field.TypeString, value)
	}
	if _u.mutation.MACAddressCleared() {
		_spec.ClearField(deviceinterface.FieldMACAddress, field.TypeString)
	}
	if value, ok := _u.mutation.InterfaceType(); ok {
		_spec.SetField(deviceinterface.FieldInterfaceType, field.TypeString, value)
	}
	if _u.mutation.InterfaceTypeCleared() {
		_spec.ClearField(deviceinterface.FieldInterfaceType, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(deviceinterface.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SpeedMbps(); ok {
		_spec.SetField(deviceinterface.FieldSpeedMbps, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedSpeedMbps(); ok {
		_spec.AddField(deviceinterface.FieldSpeedMbps, field.TypeInt32, value)
	}
	if _u.mutation.SpeedMbpsCleared() {
		_spec.ClearField(deviceinterface.FieldSpeedMbps, field.TypeInt32)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(deviceinterface.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(deviceinterface.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IfIndex(); ok {
		_spec.SetField(deviceinterface.FieldIfIndex, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedIfIndex(); ok {
		_spec.AddField(deviceinterface.FieldIfIndex, field.TypeInt32, value)
	}
	if _u.mutation.IfIndexCleared() {
		_spec.ClearField(deviceinterface.FieldIfIndex, field.TypeInt32)
	}
	if value, ok := _u.mutation.RemoteDeviceID(); ok {
		_spec.SetField(deviceinterface.FieldRemoteDeviceID, field.TypeString, value)
	}
	if _u.mutation.RemoteDeviceIDCleared() {
		_spec.ClearField(deviceinterface.FieldRemoteDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteInterfaceID(); ok {
		_spec.SetField(deviceinterface.FieldRemoteInterfaceID, field.TypeString, value)
	}
	if _u.mutation.RemoteInterfaceIDCleared() {
		_spec.ClearField(deviceinterface.FieldRemoteInterfaceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemotePortName(); ok {
		_spec.SetField(deviceinterface.FieldRemotePortName, field.TypeString, value)
	}
	if _u.mutation.RemotePortNameCleared() {
		_spec.ClearField(deviceinterface.FieldRemotePortName, field.TypeString)
	}
	if value, ok := _u.mutation.LinkSource(); ok {
		_spec.SetField(deviceinterface.FieldLinkSource, field.TypeString, value)
	}
	if _u.mutation.LinkSourceCleared() {
		_spec.ClearField(deviceinterface.FieldLinkSource, field.TypeString)
	}
	if value, ok := _u.mutation.LinkVlan(); ok {
		_spec.SetField(deviceinterface.FieldLinkVlan, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLinkVlan(); ok {
		_spec.AddField(deviceinterface.FieldLinkVlan, field.TypeInt32, value)
	}
	if _u.mutation.LinkVlanCleared() {
		_spec.ClearField(deviceinterface.FieldLinkVlan, field.TypeInt32)
	}
	if value, ok := _u.mutation.LinkLastSeen(); ok {
		_spec.SetField(deviceinterface.FieldLinkLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LinkLastSeenCleared() {
		_spec.ClearField(deviceinterface.FieldLinkLastSeen, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterface.DeviceTable,
			Columns: []string{deviceinterface.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterface.DeviceTable,
			Columns: []string{deviceinterface.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLinksIDs(); len(nodes) > 0 && !_u.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deviceinterface.LinksTable,
			Columns: []string{deviceinterface.LinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DeviceInterface{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinterface.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
