// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterface"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterfacelink"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// DeviceInterfaceLinkQuery is the builder for querying DeviceInterfaceLink entities.
type DeviceInterfaceLinkQuery struct {
	config
	ctx           *QueryContext
	order         []deviceinterfacelink.OrderOption
	inters        []Interceptor
	predicates    []predicate.DeviceInterfaceLink
	withInterface *DeviceInterfaceQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceInterfaceLinkQuery builder.
func (_q *DeviceInterfaceLinkQuery) Where(ps ...predicate.DeviceInterfaceLink) *DeviceInterfaceLinkQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DeviceInterfaceLinkQuery) Limit(limit int) *DeviceInterfaceLinkQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DeviceInterfaceLinkQuery) Offset(offset int) *DeviceInterfaceLinkQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DeviceInterfaceLinkQuery) Unique(unique bool) *DeviceInterfaceLinkQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DeviceInterfaceLinkQuery) Order(o ...deviceinterfacelink.OrderOption) *DeviceInterfaceLinkQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInterface chains the current query on the "interface" edge.
func (_q *DeviceInterfaceLinkQuery) QueryInterface() *DeviceInterfaceQuery {
	query := (&DeviceInterfaceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deviceinterfacelink.Table, deviceinterfacelink.FieldID, selector),
			sqlgraph.To(deviceinterface.Table, deviceinterface.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deviceinterfacelink.InterfaceTable, deviceinterfacelink.InterfaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceInterfaceLink entity from the query.
// Returns a *NotFoundError when no DeviceInterfaceLink was found.
func (_q *DeviceInterfaceLinkQuery) First(ctx context.Context) (*DeviceInterfaceLink, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deviceinterfacelink.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) FirstX(ctx context.Context) *DeviceInterfaceLink {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceInterfaceLink ID from the query.
// Returns a *NotFoundError when no DeviceInterfaceLink ID was found.
func (_q *DeviceInterfaceLinkQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deviceinterfacelink.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceInterfaceLink entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceInterfaceLink entity is found.
// Returns a *NotFoundError when no DeviceInterfaceLink entities are found.
func (_q *DeviceInterfaceLinkQuery) Only(ctx context.Context) (*DeviceInterfaceLink, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deviceinterfacelink.Label}
	default:
		return nil, &NotSingularError{deviceinterfacelink.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) OnlyX(ctx context.Context) *DeviceInterfaceLink {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceInterfaceLink ID in the query.
// Returns a *NotSingularError when more than one DeviceInterfaceLink ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DeviceInterfaceLinkQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deviceinterfacelink.Label}
	default:
		err = &NotSingularError{deviceinterfacelink.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceInterfaceLinks.
func (_q *DeviceInterfaceLinkQuery) All(ctx context.Context) ([]*DeviceInterfaceLink, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceInterfaceLink, *DeviceInterfaceLinkQuery]()
	return withInterceptors[[]*DeviceInterfaceLink](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) AllX(ctx context.Context) []*DeviceInterfaceLink {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceInterfaceLink IDs.
func (_q *DeviceInterfaceLinkQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(deviceinterfacelink.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DeviceInterfaceLinkQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DeviceInterfaceLinkQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DeviceInterfaceLinkQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DeviceInterfaceLinkQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceInterfaceLinkQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DeviceInterfaceLinkQuery) Clone() *DeviceInterfaceLinkQuery {
	if _q == nil {
		return nil
	}
	return &DeviceInterfaceLinkQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]deviceinterfacelink.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.DeviceInterfaceLink{}, _q.predicates...),
		withInterface: _q.withInterface.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithInterface tells the query-builder to eager-load the nodes that are connected to
// the "interface" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DeviceInterfaceLinkQuery) WithInterface(opts ...func(*DeviceInterfaceQuery)) *DeviceInterfaceLinkQuery {
	query := (&DeviceInterfaceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInterface = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceInterfaceLink.Query().
//		GroupBy(deviceinterfacelink.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DeviceInterfaceLinkQuery) GroupBy(field string, fields ...string) *DeviceInterfaceLinkGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceInterfaceLinkGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = deviceinterfacelink.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.DeviceInterfaceLink.Query().
//		Select(deviceinterfacelink.FieldCreateTime).
//		Scan(ctx, &v)
func (_q *DeviceInterfaceLinkQuery) Select(fields ...string) *DeviceInterfaceLinkSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DeviceInterfaceLinkSelect{DeviceInterfaceLinkQuery: _q}
	sbuild.label = deviceinterfacelink.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceInterfaceLinkSelect configured with the given aggregations.
func (_q *DeviceInterfaceLinkQuery) Aggregate(fns ...AggregateFunc) *DeviceInterfaceLinkSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DeviceInterfaceLinkQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !deviceinterfacelink.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DeviceInterfaceLinkQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceInterfaceLink, error) {
	var (
		nodes       = []*DeviceInterfaceLink{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withInterface != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceInterfaceLink).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceInterfaceLink{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInterface; query != nil {
		if err := _q.loadInterface(ctx, query, nodes, nil,
			func(n *DeviceInterfaceLink, e *DeviceInterface) { n.Edges.Interface = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DeviceInterfaceLinkQuery) loadInterface(ctx context.Context, query *DeviceInterfaceQuery, nodes []*DeviceInterfaceLink, init func(*DeviceInterfaceLink), assign func(*DeviceInterfaceLink, *DeviceInterface)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DeviceInterfaceLink)
	for i := range nodes {
		fk := nodes[i].InterfaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(deviceinterface.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "interface_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DeviceInterfaceLinkQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DeviceInterfaceLinkQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deviceinterfacelink.Table, deviceinterfacelink.Columns, sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceinterfacelink.FieldID)
		for i := range fields {
			if fields[i] != deviceinterfacelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withInterface != nil {
			_spec.Node.AddColumnOnce(deviceinterfacelink.FieldInterfaceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DeviceInterfaceLinkQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(deviceinterfacelink.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = deviceinterfacelink.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *DeviceInterfaceLinkQuery) ForUpdate(opts ...sql.LockOption) *DeviceInterfaceLinkQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *DeviceInterfaceLinkQuery) ForShare(opts ...sql.LockOption) *DeviceInterfaceLinkQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DeviceInterfaceLinkQuery) Modify(modifiers ...func(s *sql.Selector)) *DeviceInterfaceLinkSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DeviceInterfaceLinkGroupBy is the group-by builder for DeviceInterfaceLink entities.
type DeviceInterfaceLinkGroupBy struct {
	selector
	build *DeviceInterfaceLinkQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DeviceInterfaceLinkGroupBy) Aggregate(fns ...AggregateFunc) *DeviceInterfaceLinkGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DeviceInterfaceLinkGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceInterfaceLinkQuery, *DeviceInterfaceLinkGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DeviceInterfaceLinkGroupBy) sqlScan(ctx context.Context, root *DeviceInterfaceLinkQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceInterfaceLinkSelect is the builder for selecting fields of DeviceInterfaceLink entities.
type DeviceInterfaceLinkSelect struct {
	*DeviceInterfaceLinkQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DeviceInterfaceLinkSelect) Aggregate(fns ...AggregateFunc) *DeviceInterfaceLinkSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DeviceInterfaceLinkSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceInterfaceLinkQuery, *DeviceInterfaceLinkSelect](ctx, _s.DeviceInterfaceLinkQuery, _s, _s.inters, v)
}

func (_s *DeviceInterfaceLinkSelect) sqlScan(ctx context.Context, root *DeviceInterfaceLinkQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DeviceInterfaceLinkSelect) Modify(modifiers ...func(s *sql.Selector)) *DeviceInterfaceLinkSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
