// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterface"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/deviceinterfacelink"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// DeviceInterfaceLinkUpdate is the builder for updating DeviceInterfaceLink entities.
type DeviceInterfaceLinkUpdate struct {
	config
	hooks     []Hook
	mutation  *DeviceInterfaceLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DeviceInterfaceLinkUpdate builder.
func (_u *DeviceInterfaceLinkUpdate) Where(ps ...predicate.DeviceInterfaceLink) *DeviceInterfaceLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeviceInterfaceLinkUpdate) SetUpdateTime(v time.Time) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeviceInterfaceLinkUpdate) ClearUpdateTime() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeviceInterfaceLinkUpdate) SetDeleteTime(v time.Time) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeviceInterfaceLinkUpdate) ClearDeleteTime() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetInterfaceID sets the "interface_id" field.
func (_u *DeviceInterfaceLinkUpdate) SetInterfaceID(v string) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetInterfaceID(v)
	return _u
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableInterfaceID(v *string) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetInterfaceID(*v)
	}
	return _u
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (_u *DeviceInterfaceLinkUpdate) SetRemoteDeviceID(v string) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetRemoteDeviceID(v)
	return _u
}

// SetNillableRemoteDeviceID sets the "remote_device_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableRemoteDeviceID(v *string) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetRemoteDeviceID(*v)
	}
	return _u
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (_u *DeviceInterfaceLinkUpdate) ClearRemoteDeviceID() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearRemoteDeviceID()
	return _u
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (_u *DeviceInterfaceLinkUpdate) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetRemoteInterfaceID(v)
	return _u
}

// SetNillableRemoteInterfaceID sets the "remote_interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableRemoteInterfaceID(v *string) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetRemoteInterfaceID(*v)
	}
	return _u
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (_u *DeviceInterfaceLinkUpdate) ClearRemoteInterfaceID() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearRemoteInterfaceID()
	return _u
}

// SetRemotePortName sets the "remote_port_name" field.
func (_u *DeviceInterfaceLinkUpdate) SetRemotePortName(v string) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetRemotePortName(v)
	return _u
}

// SetNillableRemotePortName sets the "remote_port_name" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableRemotePortName(v *string) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetRemotePortName(*v)
	}
	return _u
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (_u *DeviceInterfaceLinkUpdate) ClearRemotePortName() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearRemotePortName()
	return _u
}

// SetLinkSource sets the "link_source" field.
func (_u *DeviceInterfaceLinkUpdate) SetLinkSource(v string) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetLinkSource(v)
	return _u
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableLinkSource(v *string) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetLinkSource(*v)
	}
	return _u
}

// ClearLinkSource clears the value of the "link_source" field.
func (_u *DeviceInterfaceLinkUpdate) ClearLinkSource() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearLinkSource()
	return _u
}

// SetLinkVlan sets the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdate) SetLinkVlan(v int32) *DeviceInterfaceLinkUpdate {
	_u.mutation.ResetLinkVlan()
	_u.mutation.SetLinkVlan(v)
	return _u
}

// SetNillableLinkVlan sets the "link_vlan" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableLinkVlan(v *int32) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetLinkVlan(*v)
	}
	return _u
}

// AddLinkVlan adds value to the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdate) AddLinkVlan(v int32) *DeviceInterfaceLinkUpdate {
	_u.mutation.AddLinkVlan(v)
	return _u
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdate) ClearLinkVlan() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearLinkVlan()
	return _u
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (_u *DeviceInterfaceLinkUpdate) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkUpdate {
	_u.mutation.SetLinkLastSeen(v)
	return _u
}

// SetNillableLinkLastSeen sets the "link_last_seen" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdate) SetNillableLinkLastSeen(v *time.Time) *DeviceInterfaceLinkUpdate {
	if v != nil {
		_u.SetLinkLastSeen(*v)
	}
	return _u
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (_u *DeviceInterfaceLinkUpdate) ClearLinkLastSeen() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearLinkLastSeen()
	return _u
}

// SetInterface sets the "interface" edge to the DeviceInterface entity.
func (_u *DeviceInterfaceLinkUpdate) SetInterface(v *DeviceInterface) *DeviceInterfaceLinkUpdate {
	return _u.SetInterfaceID(v.ID)
}

// Mutation returns the DeviceInterfaceLinkMutation object of the builder.
func (_u *DeviceInterfaceLinkUpdate) Mutation() *DeviceInterfaceLinkMutation {
	return _u.mutation
}

// ClearInterface clears the "interface" edge to the DeviceInterface entity.
func (_u *DeviceInterfaceLinkUpdate) ClearInterface() *DeviceInterfaceLinkUpdate {
	_u.mutation.ClearInterface()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceInterfaceLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceInterfaceLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceInterfaceLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceInterfaceLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceInterfaceLinkUpdate) check() error {
	if v, ok := _u.mutation.InterfaceID(); ok {
		if err := deviceinterfacelink.InterfaceIDValidator(v); err != nil {
			return &ValidationError{Name: "interface_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterfaceLink.interface_id": %w`, err)}
		}
	}
	if _u.mutation.InterfaceCleared() && len(_u.mutation.InterfaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceInterfaceLink.interface"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceInterfaceLinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceInterfaceLinkUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceInterfaceLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deviceinterfacelink.Table, deviceinterfacelink.Columns, sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RemoteDeviceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteDeviceID, field.TypeString, value)
	}
	if _u.mutation.RemoteDeviceIDCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemoteDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteInterfaceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteInterfaceID, field.TypeString, value)
	}
	if _u.mutation.RemoteInterfaceIDCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemoteInterfaceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemotePortName(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemotePortName, field.TypeString, value)
	}
	if _u.mutation.RemotePortNameCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemotePortName, field.TypeString)
	}
	if value, ok := _u.mutation.LinkSource(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkSource, field.TypeString, value)
	}
	if _u.mutation.LinkSourceCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkSource, field.TypeString)
	}
	if value, ok := _u.mutation.LinkVlan(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLinkVlan(); ok {
		_spec.AddField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32, value)
	}
	if _u.mutation.LinkVlanCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32)
	}
	if value, ok := _u.mutation.LinkLastSeen(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LinkLastSeenCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkLastSeen, field.TypeTime)
	}
	if _u.mutation.InterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterfacelink.InterfaceTable,
			Columns: []string{deviceinterfacelink.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterfacelink.InterfaceTable,
			Columns: []string{deviceinterfacelink.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinterfacelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceInterfaceLinkUpdateOne is the builder for updating a single DeviceInterfaceLink entity.
type DeviceInterfaceLinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DeviceInterfaceLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetUpdateTime(v time.Time) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableUpdateTime(v *time.Time) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearUpdateTime() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetDeleteTime(v time.Time) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableDeleteTime(v *time.Time) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearDeleteTime() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetInterfaceID sets the "interface_id" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetInterfaceID(v string) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetInterfaceID(v)
	return _u
}

// SetNillableInterfaceID sets the "interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableInterfaceID(v *string) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetInterfaceID(*v)
	}
	return _u
}

// SetRemoteDeviceID sets the "remote_device_id" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetRemoteDeviceID(v string) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetRemoteDeviceID(v)
	return _u
}

// SetNillableRemoteDeviceID sets the "remote_device_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableRemoteDeviceID(v *string) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetRemoteDeviceID(*v)
	}
	return _u
}

// ClearRemoteDeviceID clears the value of the "remote_device_id" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearRemoteDeviceID() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearRemoteDeviceID()
	return _u
}

// SetRemoteInterfaceID sets the "remote_interface_id" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetRemoteInterfaceID(v string) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetRemoteInterfaceID(v)
	return _u
}

// SetNillableRemoteInterfaceID sets the "remote_interface_id" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableRemoteInterfaceID(v *string) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetRemoteInterfaceID(*v)
	}
	return _u
}

// ClearRemoteInterfaceID clears the value of the "remote_interface_id" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearRemoteInterfaceID() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearRemoteInterfaceID()
	return _u
}

// SetRemotePortName sets the "remote_port_name" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetRemotePortName(v string) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetRemotePortName(v)
	return _u
}

// SetNillableRemotePortName sets the "remote_port_name" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableRemotePortName(v *string) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetRemotePortName(*v)
	}
	return _u
}

// ClearRemotePortName clears the value of the "remote_port_name" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearRemotePortName() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearRemotePortName()
	return _u
}

// SetLinkSource sets the "link_source" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetLinkSource(v string) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetLinkSource(v)
	return _u
}

// SetNillableLinkSource sets the "link_source" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableLinkSource(v *string) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetLinkSource(*v)
	}
	return _u
}

// ClearLinkSource clears the value of the "link_source" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearLinkSource() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearLinkSource()
	return _u
}

// SetLinkVlan sets the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetLinkVlan(v int32) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ResetLinkVlan()
	_u.mutation.SetLinkVlan(v)
	return _u
}

// SetNillableLinkVlan sets the "link_vlan" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableLinkVlan(v *int32) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetLinkVlan(*v)
	}
	return _u
}

// AddLinkVlan adds value to the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdateOne) AddLinkVlan(v int32) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.AddLinkVlan(v)
	return _u
}

// ClearLinkVlan clears the value of the "link_vlan" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearLinkVlan() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearLinkVlan()
	return _u
}

// SetLinkLastSeen sets the "link_last_seen" field.
func (_u *DeviceInterfaceLinkUpdateOne) SetLinkLastSeen(v time.Time) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.SetLinkLastSeen(v)
	return _u
}

// SetNillableLinkLastSeen sets the "link_last_seen" field if the given value is not nil.
func (_u *DeviceInterfaceLinkUpdateOne) SetNillableLinkLastSeen(v *time.Time) *DeviceInterfaceLinkUpdateOne {
	if v != nil {
		_u.SetLinkLastSeen(*v)
	}
	return _u
}

// ClearLinkLastSeen clears the value of the "link_last_seen" field.
func (_u *DeviceInterfaceLinkUpdateOne) ClearLinkLastSeen() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearLinkLastSeen()
	return _u
}

// SetInterface sets the "interface" edge to the DeviceInterface entity.
func (_u *DeviceInterfaceLinkUpdateOne) SetInterface(v *DeviceInterface) *DeviceInterfaceLinkUpdateOne {
	return _u.SetInterfaceID(v.ID)
}

// Mutation returns the DeviceInterfaceLinkMutation object of the builder.
func (_u *DeviceInterfaceLinkUpdateOne) Mutation() *DeviceInterfaceLinkMutation {
	return _u.mutation
}

// ClearInterface clears the "interface" edge to the DeviceInterface entity.
func (_u *DeviceInterfaceLinkUpdateOne) ClearInterface() *DeviceInterfaceLinkUpdateOne {
	_u.mutation.ClearInterface()
	return _u
}

// Where appends a list predicates to the DeviceInterfaceLinkUpdate builder.
func (_u *DeviceInterfaceLinkUpdateOne) Where(ps ...predicate.DeviceInterfaceLink) *DeviceInterfaceLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceInterfaceLinkUpdateOne) Select(field string, fields ...string) *DeviceInterfaceLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeviceInterfaceLink entity.
func (_u *DeviceInterfaceLinkUpdateOne) Save(ctx context.Context) (*DeviceInterfaceLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceInterfaceLinkUpdateOne) SaveX(ctx context.Context) *DeviceInterfaceLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceInterfaceLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceInterfaceLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceInterfaceLinkUpdateOne) check() error {
	if v, ok := _u.mutation.InterfaceID(); ok {
		if err := deviceinterfacelink.InterfaceIDValidator(v); err != nil {
			return &ValidationError{Name: "interface_id", err: fmt.Errorf(`ent: validator failed for field "DeviceInterfaceLink.interface_id": %w`, err)}
		}
	}
	if _u.mutation.InterfaceCleared() && len(_u.mutation.InterfaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeviceInterfaceLink.interface"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DeviceInterfaceLinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DeviceInterfaceLinkUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DeviceInterfaceLinkUpdateOne) sqlSave(ctx context.Context) (_node *DeviceInterfaceLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deviceinterfacelink.Table, deviceinterfacelink.Columns, sqlgraph.NewFieldSpec(deviceinterfacelink.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceInterfaceLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceinterfacelink.FieldID)
		for _, f := range fields {
			if !deviceinterfacelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deviceinterfacelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(deviceinterfacelink.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(deviceinterfacelink.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RemoteDeviceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteDeviceID, field.TypeString, value)
	}
	if _u.mutation.RemoteDeviceIDCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemoteDeviceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteInterfaceID(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemoteInterfaceID, field.TypeString, value)
	}
	if _u.mutation.RemoteInterfaceIDCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemoteInterfaceID, field.TypeString)
	}
	if value, ok := _u.mutation.RemotePortName(); ok {
		_spec.SetField(deviceinterfacelink.FieldRemotePortName, field.TypeString, value)
	}
	if _u.mutation.RemotePortNameCleared() {
		_spec.ClearField(deviceinterfacelink.FieldRemotePortName, field.TypeString)
	}
	if value, ok := _u.mutation.LinkSource(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkSource, field.TypeString, value)
	}
	if _u.mutation.LinkSourceCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkSource, field.TypeString)
	}
	if value, ok := _u.mutation.LinkVlan(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedLinkVlan(); ok {
		_spec.AddField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32, value)
	}
	if _u.mutation.LinkVlanCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkVlan, field.TypeInt32)
	}
	if value, ok := _u.mutation.LinkLastSeen(); ok {
		_spec.SetField(deviceinterfacelink.FieldLinkLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LinkLastSeenCleared() {
		_spec.ClearField(deviceinterfacelink.FieldLinkLastSeen, field.TypeTime)
	}
	if _u.mutation.InterfaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterfacelink.InterfaceTable,
			Columns: []string{deviceinterfacelink.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InterfaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deviceinterfacelink.InterfaceTable,
			Columns: []string{deviceinterfacelink.InterfaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deviceinterface.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &DeviceInterfaceLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deviceinterfacelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
