// Code generated by ent, DO NOT EDIT.

package deviceinterface

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deviceinterface type in the database.
	Label = "device_interface"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldMACAddress holds the string denoting the mac_address field in the database.
	FieldMACAddress = "mac_address"
	// FieldInterfaceType holds the string denoting the interface_type field in the database.
	FieldInterfaceType = "interface_type"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSpeedMbps holds the string denoting the speed_mbps field in the database.
	FieldSpeedMbps = "speed_mbps"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldIfIndex holds the string denoting the if_index field in the database.
	FieldIfIndex = "if_index"
	// FieldRemoteDeviceID holds the string denoting the remote_device_id field in the database.
	FieldRemoteDeviceID = "remote_device_id"
	// FieldRemoteInterfaceID holds the string denoting the remote_interface_id field in the database.
	FieldRemoteInterfaceID = "remote_interface_id"
	// FieldRemotePortName holds the string denoting the remote_port_name field in the database.
	FieldRemotePortName = "remote_port_name"
	// FieldLinkSource holds the string denoting the link_source field in the database.
	FieldLinkSource = "link_source"
	// FieldLinkVlan holds the string denoting the link_vlan field in the database.
	FieldLinkVlan = "link_vlan"
	// FieldLinkLastSeen holds the string denoting the link_last_seen field in the database.
	FieldLinkLastSeen = "link_last_seen"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// EdgeLinks holds the string denoting the links edge name in mutations.
	EdgeLinks = "links"
	// Table holds the table name of the deviceinterface in the database.
	Table = "ipam_device_interfaces"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "ipam_device_interfaces"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "ipam_devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
	// LinksTable is the table that holds the links relation/edge.
	LinksTable = "ipam_device_interface_links"
	// LinksInverseTable is the table name for the DeviceInterfaceLink entity.
	// It exists in this package in order to avoid circular dependency with the "deviceinterfacelink" package.
	LinksInverseTable = "ipam_device_interface_links"
	// LinksColumn is the table column denoting the links relation/edge.
	LinksColumn = "interface_id"
)

// Columns holds all SQL columns for deviceinterface fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldDeviceID,
	FieldName,
	FieldMACAddress,
	FieldInterfaceType,
	FieldEnabled,
	FieldSpeedMbps,
	FieldDescription,
	FieldIfIndex,
	FieldRemoteDeviceID,
	FieldRemoteInterfaceID,
	FieldRemotePortName,
	FieldLinkSource,
	FieldLinkVlan,
	FieldLinkLastSeen,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	DeviceIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the DeviceInterface queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMACAddress orders the results by the mac_address field.
func ByMACAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMACAddress, opts...).ToFunc()
}

// ByInterfaceType orders the results by the interface_type field.
func ByInterfaceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterfaceType, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySpeedMbps orders the results by the speed_mbps field.
func BySpeedMbps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeedMbps, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByIfIndex orders the results by the if_index field.
func ByIfIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIfIndex, opts...).ToFunc()
}

// ByRemoteDeviceID orders the results by the remote_device_id field.
func ByRemoteDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteDeviceID, opts...).ToFunc()
}

// ByRemoteInterfaceID orders the results by the remote_interface_id field.
func ByRemoteInterfaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteInterfaceID, opts...).ToFunc()
}

// ByRemotePortName orders the results by the remote_port_name field.
func ByRemotePortName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemotePortName, opts...).ToFunc()
}

// ByLinkSource orders the results by the link_source field.
func ByLinkSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkSource, opts...).ToFunc()
}

// ByLinkVlan orders the results by the link_vlan field.
func ByLinkVlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkVlan, opts...).ToFunc()
}

// ByLinkLastSeen orders the results by the link_last_seen field.
func ByLinkLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkLastSeen, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}

// ByLinksCount orders the results by links count.
func ByLinksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLinksStep(), opts...)
	}
}

// ByLinks orders the results by links terms.
func ByLinks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
func newLinksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LinksTable, LinksColumn),
	)
}
