// Code generated by ent, DO NOT EDIT.

package devicepackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldTenantID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDeviceID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldName, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldCurrentVersion, v))
}

// AvailableVersion applies equality check predicate on the "available_version" field. It's identical to AvailableVersionEQ.
func AvailableVersion(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldAvailableVersion, v))
}

// NeedsUpdate applies equality check predicate on the "needs_update" field. It's identical to NeedsUpdateEQ.
func NeedsUpdate(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldNeedsUpdate, v))
}

// IsSecurityUpdate applies equality check predicate on the "is_security_update" field. It's identical to IsSecurityUpdateEQ.
func IsSecurityUpdate(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldIsSecurityUpdate, v))
}

// PackageManager applies equality check predicate on the "package_manager" field. It's identical to PackageManagerEQ.
func PackageManager(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldPackageManager, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDescription, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldTenantID))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldDeviceID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldName, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldCurrentVersion, v))
}

// CurrentVersionContains applies the Contains predicate on the "current_version" field.
func CurrentVersionContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldCurrentVersion, v))
}

// CurrentVersionHasPrefix applies the HasPrefix predicate on the "current_version" field.
func CurrentVersionHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldCurrentVersion, v))
}

// CurrentVersionHasSuffix applies the HasSuffix predicate on the "current_version" field.
func CurrentVersionHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldCurrentVersion, v))
}

// CurrentVersionIsNil applies the IsNil predicate on the "current_version" field.
func CurrentVersionIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldCurrentVersion))
}

// CurrentVersionNotNil applies the NotNil predicate on the "current_version" field.
func CurrentVersionNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldCurrentVersion))
}

// CurrentVersionEqualFold applies the EqualFold predicate on the "current_version" field.
func CurrentVersionEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldCurrentVersion, v))
}

// CurrentVersionContainsFold applies the ContainsFold predicate on the "current_version" field.
func CurrentVersionContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldCurrentVersion, v))
}

// AvailableVersionEQ applies the EQ predicate on the "available_version" field.
func AvailableVersionEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldAvailableVersion, v))
}

// AvailableVersionNEQ applies the NEQ predicate on the "available_version" field.
func AvailableVersionNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldAvailableVersion, v))
}

// AvailableVersionIn applies the In predicate on the "available_version" field.
func AvailableVersionIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldAvailableVersion, vs...))
}

// AvailableVersionNotIn applies the NotIn predicate on the "available_version" field.
func AvailableVersionNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldAvailableVersion, vs...))
}

// AvailableVersionGT applies the GT predicate on the "available_version" field.
func AvailableVersionGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldAvailableVersion, v))
}

// AvailableVersionGTE applies the GTE predicate on the "available_version" field.
func AvailableVersionGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldAvailableVersion, v))
}

// AvailableVersionLT applies the LT predicate on the "available_version" field.
func AvailableVersionLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldAvailableVersion, v))
}

// AvailableVersionLTE applies the LTE predicate on the "available_version" field.
func AvailableVersionLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldAvailableVersion, v))
}

// AvailableVersionContains applies the Contains predicate on the "available_version" field.
func AvailableVersionContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldAvailableVersion, v))
}

// AvailableVersionHasPrefix applies the HasPrefix predicate on the "available_version" field.
func AvailableVersionHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldAvailableVersion, v))
}

// AvailableVersionHasSuffix applies the HasSuffix predicate on the "available_version" field.
func AvailableVersionHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldAvailableVersion, v))
}

// AvailableVersionIsNil applies the IsNil predicate on the "available_version" field.
func AvailableVersionIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldAvailableVersion))
}

// AvailableVersionNotNil applies the NotNil predicate on the "available_version" field.
func AvailableVersionNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldAvailableVersion))
}

// AvailableVersionEqualFold applies the EqualFold predicate on the "available_version" field.
func AvailableVersionEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldAvailableVersion, v))
}

// AvailableVersionContainsFold applies the ContainsFold predicate on the "available_version" field.
func AvailableVersionContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldAvailableVersion, v))
}

// NeedsUpdateEQ applies the EQ predicate on the "needs_update" field.
func NeedsUpdateEQ(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldNeedsUpdate, v))
}

// NeedsUpdateNEQ applies the NEQ predicate on the "needs_update" field.
func NeedsUpdateNEQ(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldNeedsUpdate, v))
}

// IsSecurityUpdateEQ applies the EQ predicate on the "is_security_update" field.
func IsSecurityUpdateEQ(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldIsSecurityUpdate, v))
}

// IsSecurityUpdateNEQ applies the NEQ predicate on the "is_security_update" field.
func IsSecurityUpdateNEQ(v bool) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldIsSecurityUpdate, v))
}

// PackageManagerEQ applies the EQ predicate on the "package_manager" field.
func PackageManagerEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldPackageManager, v))
}

// PackageManagerNEQ applies the NEQ predicate on the "package_manager" field.
func PackageManagerNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldPackageManager, v))
}

// PackageManagerIn applies the In predicate on the "package_manager" field.
func PackageManagerIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldPackageManager, vs...))
}

// PackageManagerNotIn applies the NotIn predicate on the "package_manager" field.
func PackageManagerNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldPackageManager, vs...))
}

// PackageManagerGT applies the GT predicate on the "package_manager" field.
func PackageManagerGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldPackageManager, v))
}

// PackageManagerGTE applies the GTE predicate on the "package_manager" field.
func PackageManagerGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldPackageManager, v))
}

// PackageManagerLT applies the LT predicate on the "package_manager" field.
func PackageManagerLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldPackageManager, v))
}

// PackageManagerLTE applies the LTE predicate on the "package_manager" field.
func PackageManagerLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldPackageManager, v))
}

// PackageManagerContains applies the Contains predicate on the "package_manager" field.
func PackageManagerContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldPackageManager, v))
}

// PackageManagerHasPrefix applies the HasPrefix predicate on the "package_manager" field.
func PackageManagerHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldPackageManager, v))
}

// PackageManagerHasSuffix applies the HasSuffix predicate on the "package_manager" field.
func PackageManagerHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldPackageManager, v))
}

// PackageManagerIsNil applies the IsNil predicate on the "package_manager" field.
func PackageManagerIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldPackageManager))
}

// PackageManagerNotNil applies the NotNil predicate on the "package_manager" field.
func PackageManagerNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldPackageManager))
}

// PackageManagerEqualFold applies the EqualFold predicate on the "package_manager" field.
func PackageManagerEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldPackageManager, v))
}

// PackageManagerContainsFold applies the ContainsFold predicate on the "package_manager" field.
func PackageManagerContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldPackageManager, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DevicePackage {
	return predicate.DevicePackage(sql.FieldContainsFold(FieldDescription, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DevicePackage) predicate.DevicePackage {
	return predicate.DevicePackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DevicePackage) predicate.DevicePackage {
	return predicate.DevicePackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DevicePackage) predicate.DevicePackage {
	return predicate.DevicePackage(sql.NotPredicates(p))
}
