// Code generated by ent, DO NOT EDIT.

package deviceinterfacelink

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deviceinterfacelink type in the database.
	Label = "device_interface_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldInterfaceID holds the string denoting the interface_id field in the database.
	FieldInterfaceID = "interface_id"
	// FieldRemoteDeviceID holds the string denoting the remote_device_id field in the database.
	FieldRemoteDeviceID = "remote_device_id"
	// FieldRemoteInterfaceID holds the string denoting the remote_interface_id field in the database.
	FieldRemoteInterfaceID = "remote_interface_id"
	// FieldRemotePortName holds the string denoting the remote_port_name field in the database.
	FieldRemotePortName = "remote_port_name"
	// FieldLinkSource holds the string denoting the link_source field in the database.
	FieldLinkSource = "link_source"
	// FieldLinkVlan holds the string denoting the link_vlan field in the database.
	FieldLinkVlan = "link_vlan"
	// FieldLinkLastSeen holds the string denoting the link_last_seen field in the database.
	FieldLinkLastSeen = "link_last_seen"
	// EdgeInterface holds the string denoting the interface edge name in mutations.
	EdgeInterface = "interface"
	// Table holds the table name of the deviceinterfacelink in the database.
	Table = "ipam_device_interface_links"
	// InterfaceTable is the table that holds the interface relation/edge.
	InterfaceTable = "ipam_device_interface_links"
	// InterfaceInverseTable is the table name for the DeviceInterface entity.
	// It exists in this package in order to avoid circular dependency with the "deviceinterface" package.
	InterfaceInverseTable = "ipam_device_interfaces"
	// InterfaceColumn is the table column denoting the interface relation/edge.
	InterfaceColumn = "interface_id"
)

// Columns holds all SQL columns for deviceinterfacelink fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldInterfaceID,
	FieldRemoteDeviceID,
	FieldRemoteInterfaceID,
	FieldRemotePortName,
	FieldLinkSource,
	FieldLinkVlan,
	FieldLinkLastSeen,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// InterfaceIDValidator is a validator for the "interface_id" field. It is called by the builders before save.
	InterfaceIDValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the DeviceInterfaceLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByInterfaceID orders the results by the interface_id field.
func ByInterfaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterfaceID, opts...).ToFunc()
}

// ByRemoteDeviceID orders the results by the remote_device_id field.
func ByRemoteDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteDeviceID, opts...).ToFunc()
}

// ByRemoteInterfaceID orders the results by the remote_interface_id field.
func ByRemoteInterfaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteInterfaceID, opts...).ToFunc()
}

// ByRemotePortName orders the results by the remote_port_name field.
func ByRemotePortName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemotePortName, opts...).ToFunc()
}

// ByLinkSource orders the results by the link_source field.
func ByLinkSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkSource, opts...).ToFunc()
}

// ByLinkVlan orders the results by the link_vlan field.
func ByLinkVlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkVlan, opts...).ToFunc()
}

// ByLinkLastSeen orders the results by the link_last_seen field.
func ByLinkLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkLastSeen, opts...).ToFunc()
}

// ByInterfaceField orders the results by interface field.
func ByInterfaceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInterfaceStep(), sql.OrderByField(field, opts...))
	}
}
func newInterfaceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InterfaceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InterfaceTable, InterfaceColumn),
	)
}
