// Code generated by ent, DO NOT EDIT.

package deviceinterfacelink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-tangra/go-tangra-ipam/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldDeleteTime, v))
}

// InterfaceID applies equality check predicate on the "interface_id" field. It's identical to InterfaceIDEQ.
func InterfaceID(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldInterfaceID, v))
}

// RemoteDeviceID applies equality check predicate on the "remote_device_id" field. It's identical to RemoteDeviceIDEQ.
func RemoteDeviceID(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemoteDeviceID, v))
}

// RemoteInterfaceID applies equality check predicate on the "remote_interface_id" field. It's identical to RemoteInterfaceIDEQ.
func RemoteInterfaceID(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemoteInterfaceID, v))
}

// RemotePortName applies equality check predicate on the "remote_port_name" field. It's identical to RemotePortNameEQ.
func RemotePortName(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemotePortName, v))
}

// LinkSource applies equality check predicate on the "link_source" field. It's identical to LinkSourceEQ.
func LinkSource(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkSource, v))
}

// LinkVlan applies equality check predicate on the "link_vlan" field. It's identical to LinkVlanEQ.
func LinkVlan(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkVlan, v))
}

// LinkLastSeen applies equality check predicate on the "link_last_seen" field. It's identical to LinkLastSeenEQ.
func LinkLastSeen(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkLastSeen, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldDeleteTime))
}

// InterfaceIDEQ applies the EQ predicate on the "interface_id" field.
func InterfaceIDEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldInterfaceID, v))
}

// InterfaceIDNEQ applies the NEQ predicate on the "interface_id" field.
func InterfaceIDNEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldInterfaceID, v))
}

// InterfaceIDIn applies the In predicate on the "interface_id" field.
func InterfaceIDIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldInterfaceID, vs...))
}

// InterfaceIDNotIn applies the NotIn predicate on the "interface_id" field.
func InterfaceIDNotIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldInterfaceID, vs...))
}

// InterfaceIDGT applies the GT predicate on the "interface_id" field.
func InterfaceIDGT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldInterfaceID, v))
}

// InterfaceIDGTE applies the GTE predicate on the "interface_id" field.
func InterfaceIDGTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldInterfaceID, v))
}

// InterfaceIDLT applies the LT predicate on the "interface_id" field.
func InterfaceIDLT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldInterfaceID, v))
}

// InterfaceIDLTE applies the LTE predicate on the "interface_id" field.
func InterfaceIDLTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldInterfaceID, v))
}

// InterfaceIDContains applies the Contains predicate on the "interface_id" field.
func InterfaceIDContains(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContains(FieldInterfaceID, v))
}

// InterfaceIDHasPrefix applies the HasPrefix predicate on the "interface_id" field.
func InterfaceIDHasPrefix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasPrefix(FieldInterfaceID, v))
}

// InterfaceIDHasSuffix applies the HasSuffix predicate on the "interface_id" field.
func InterfaceIDHasSuffix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasSuffix(FieldInterfaceID, v))
}

// InterfaceIDEqualFold applies the EqualFold predicate on the "interface_id" field.
func InterfaceIDEqualFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldInterfaceID, v))
}

// InterfaceIDContainsFold applies the ContainsFold predicate on the "interface_id" field.
func InterfaceIDContainsFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldInterfaceID, v))
}

// RemoteDeviceIDEQ applies the EQ predicate on the "remote_device_id" field.
func RemoteDeviceIDEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDNEQ applies the NEQ predicate on the "remote_device_id" field.
func RemoteDeviceIDNEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDIn applies the In predicate on the "remote_device_id" field.
func RemoteDeviceIDIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldRemoteDeviceID, vs...))
}

// RemoteDeviceIDNotIn applies the NotIn predicate on the "remote_device_id" field.
func RemoteDeviceIDNotIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldRemoteDeviceID, vs...))
}

// RemoteDeviceIDGT applies the GT predicate on the "remote_device_id" field.
func RemoteDeviceIDGT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDGTE applies the GTE predicate on the "remote_device_id" field.
func RemoteDeviceIDGTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDLT applies the LT predicate on the "remote_device_id" field.
func RemoteDeviceIDLT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDLTE applies the LTE predicate on the "remote_device_id" field.
func RemoteDeviceIDLTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDContains applies the Contains predicate on the "remote_device_id" field.
func RemoteDeviceIDContains(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContains(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDHasPrefix applies the HasPrefix predicate on the "remote_device_id" field.
func RemoteDeviceIDHasPrefix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasPrefix(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDHasSuffix applies the HasSuffix predicate on the "remote_device_id" field.
func RemoteDeviceIDHasSuffix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasSuffix(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDIsNil applies the IsNil predicate on the "remote_device_id" field.
func RemoteDeviceIDIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldRemoteDeviceID))
}

// RemoteDeviceIDNotNil applies the NotNil predicate on the "remote_device_id" field.
func RemoteDeviceIDNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldRemoteDeviceID))
}

// RemoteDeviceIDEqualFold applies the EqualFold predicate on the "remote_device_id" field.
func RemoteDeviceIDEqualFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldRemoteDeviceID, v))
}

// RemoteDeviceIDContainsFold applies the ContainsFold predicate on the "remote_device_id" field.
func RemoteDeviceIDContainsFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldRemoteDeviceID, v))
}

// RemoteInterfaceIDEQ applies the EQ predicate on the "remote_interface_id" field.
func RemoteInterfaceIDEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDNEQ applies the NEQ predicate on the "remote_interface_id" field.
func RemoteInterfaceIDNEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDIn applies the In predicate on the "remote_interface_id" field.
func RemoteInterfaceIDIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldRemoteInterfaceID, vs...))
}

// RemoteInterfaceIDNotIn applies the NotIn predicate on the "remote_interface_id" field.
func RemoteInterfaceIDNotIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldRemoteInterfaceID, vs...))
}

// RemoteInterfaceIDGT applies the GT predicate on the "remote_interface_id" field.
func RemoteInterfaceIDGT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDGTE applies the GTE predicate on the "remote_interface_id" field.
func RemoteInterfaceIDGTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDLT applies the LT predicate on the "remote_interface_id" field.
func RemoteInterfaceIDLT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDLTE applies the LTE predicate on the "remote_interface_id" field.
func RemoteInterfaceIDLTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDContains applies the Contains predicate on the "remote_interface_id" field.
func RemoteInterfaceIDContains(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContains(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDHasPrefix applies the HasPrefix predicate on the "remote_interface_id" field.
func RemoteInterfaceIDHasPrefix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasPrefix(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDHasSuffix applies the HasSuffix predicate on the "remote_interface_id" field.
func RemoteInterfaceIDHasSuffix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasSuffix(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDIsNil applies the IsNil predicate on the "remote_interface_id" field.
func RemoteInterfaceIDIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldRemoteInterfaceID))
}

// RemoteInterfaceIDNotNil applies the NotNil predicate on the "remote_interface_id" field.
func RemoteInterfaceIDNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldRemoteInterfaceID))
}

// RemoteInterfaceIDEqualFold applies the EqualFold predicate on the "remote_interface_id" field.
func RemoteInterfaceIDEqualFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldRemoteInterfaceID, v))
}

// RemoteInterfaceIDContainsFold applies the ContainsFold predicate on the "remote_interface_id" field.
func RemoteInterfaceIDContainsFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldRemoteInterfaceID, v))
}

// RemotePortNameEQ applies the EQ predicate on the "remote_port_name" field.
func RemotePortNameEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldRemotePortName, v))
}

// RemotePortNameNEQ applies the NEQ predicate on the "remote_port_name" field.
func RemotePortNameNEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldRemotePortName, v))
}

// RemotePortNameIn applies the In predicate on the "remote_port_name" field.
func RemotePortNameIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldRemotePortName, vs...))
}

// RemotePortNameNotIn applies the NotIn predicate on the "remote_port_name" field.
func RemotePortNameNotIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldRemotePortName, vs...))
}

// RemotePortNameGT applies the GT predicate on the "remote_port_name" field.
func RemotePortNameGT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldRemotePortName, v))
}

// RemotePortNameGTE applies the GTE predicate on the "remote_port_name" field.
func RemotePortNameGTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldRemotePortName, v))
}

// RemotePortNameLT applies the LT predicate on the "remote_port_name" field.
func RemotePortNameLT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldRemotePortName, v))
}

// RemotePortNameLTE applies the LTE predicate on the "remote_port_name" field.
func RemotePortNameLTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldRemotePortName, v))
}

// RemotePortNameContains applies the Contains predicate on the "remote_port_name" field.
func RemotePortNameContains(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContains(FieldRemotePortName, v))
}

// RemotePortNameHasPrefix applies the HasPrefix predicate on the "remote_port_name" field.
func RemotePortNameHasPrefix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasPrefix(FieldRemotePortName, v))
}

// RemotePortNameHasSuffix applies the HasSuffix predicate on the "remote_port_name" field.
func RemotePortNameHasSuffix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasSuffix(FieldRemotePortName, v))
}

// RemotePortNameIsNil applies the IsNil predicate on the "remote_port_name" field.
func RemotePortNameIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldRemotePortName))
}

// RemotePortNameNotNil applies the NotNil predicate on the "remote_port_name" field.
func RemotePortNameNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldRemotePortName))
}

// RemotePortNameEqualFold applies the EqualFold predicate on the "remote_port_name" field.
func RemotePortNameEqualFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldRemotePortName, v))
}

// RemotePortNameContainsFold applies the ContainsFold predicate on the "remote_port_name" field.
func RemotePortNameContainsFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldRemotePortName, v))
}

// LinkSourceEQ applies the EQ predicate on the "link_source" field.
func LinkSourceEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkSource, v))
}

// LinkSourceNEQ applies the NEQ predicate on the "link_source" field.
func LinkSourceNEQ(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldLinkSource, v))
}

// LinkSourceIn applies the In predicate on the "link_source" field.
func LinkSourceIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldLinkSource, vs...))
}

// LinkSourceNotIn applies the NotIn predicate on the "link_source" field.
func LinkSourceNotIn(vs ...string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldLinkSource, vs...))
}

// LinkSourceGT applies the GT predicate on the "link_source" field.
func LinkSourceGT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldLinkSource, v))
}

// LinkSourceGTE applies the GTE predicate on the "link_source" field.
func LinkSourceGTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldLinkSource, v))
}

// LinkSourceLT applies the LT predicate on the "link_source" field.
func LinkSourceLT(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldLinkSource, v))
}

// LinkSourceLTE applies the LTE predicate on the "link_source" field.
func LinkSourceLTE(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldLinkSource, v))
}

// LinkSourceContains applies the Contains predicate on the "link_source" field.
func LinkSourceContains(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContains(FieldLinkSource, v))
}

// LinkSourceHasPrefix applies the HasPrefix predicate on the "link_source" field.
func LinkSourceHasPrefix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasPrefix(FieldLinkSource, v))
}

// LinkSourceHasSuffix applies the HasSuffix predicate on the "link_source" field.
func LinkSourceHasSuffix(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldHasSuffix(FieldLinkSource, v))
}

// LinkSourceIsNil applies the IsNil predicate on the "link_source" field.
func LinkSourceIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldLinkSource))
}

// LinkSourceNotNil applies the NotNil predicate on the "link_source" field.
func LinkSourceNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldLinkSource))
}

// LinkSourceEqualFold applies the EqualFold predicate on the "link_source" field.
func LinkSourceEqualFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEqualFold(FieldLinkSource, v))
}

// LinkSourceContainsFold applies the ContainsFold predicate on the "link_source" field.
func LinkSourceContainsFold(v string) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldContainsFold(FieldLinkSource, v))
}

// LinkVlanEQ applies the EQ predicate on the "link_vlan" field.
func LinkVlanEQ(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkVlan, v))
}

// LinkVlanNEQ applies the NEQ predicate on the "link_vlan" field.
func LinkVlanNEQ(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldLinkVlan, v))
}

// LinkVlanIn applies the In predicate on the "link_vlan" field.
func LinkVlanIn(vs ...int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldLinkVlan, vs...))
}

// LinkVlanNotIn applies the NotIn predicate on the "link_vlan" field.
func LinkVlanNotIn(vs ...int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldLinkVlan, vs...))
}

// LinkVlanGT applies the GT predicate on the "link_vlan" field.
func LinkVlanGT(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldLinkVlan, v))
}

// LinkVlanGTE applies the GTE predicate on the "link_vlan" field.
func LinkVlanGTE(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldLinkVlan, v))
}

// LinkVlanLT applies the LT predicate on the "link_vlan" field.
func LinkVlanLT(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldLinkVlan, v))
}

// LinkVlanLTE applies the LTE predicate on the "link_vlan" field.
func LinkVlanLTE(v int32) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldLinkVlan, v))
}

// LinkVlanIsNil applies the IsNil predicate on the "link_vlan" field.
func LinkVlanIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldLinkVlan))
}

// LinkVlanNotNil applies the NotNil predicate on the "link_vlan" field.
func LinkVlanNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldLinkVlan))
}

// LinkLastSeenEQ applies the EQ predicate on the "link_last_seen" field.
func LinkLastSeenEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldEQ(FieldLinkLastSeen, v))
}

// LinkLastSeenNEQ applies the NEQ predicate on the "link_last_seen" field.
func LinkLastSeenNEQ(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNEQ(FieldLinkLastSeen, v))
}

// LinkLastSeenIn applies the In predicate on the "link_last_seen" field.
func LinkLastSeenIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIn(FieldLinkLastSeen, vs...))
}

// LinkLastSeenNotIn applies the NotIn predicate on the "link_last_seen" field.
func LinkLastSeenNotIn(vs ...time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotIn(FieldLinkLastSeen, vs...))
}

// LinkLastSeenGT applies the GT predicate on the "link_last_seen" field.
func LinkLastSeenGT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGT(FieldLinkLastSeen, v))
}

// LinkLastSeenGTE applies the GTE predicate on the "link_last_seen" field.
func LinkLastSeenGTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldGTE(FieldLinkLastSeen, v))
}

// LinkLastSeenLT applies the LT predicate on the "link_last_seen" field.
func LinkLastSeenLT(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLT(FieldLinkLastSeen, v))
}

// LinkLastSeenLTE applies the LTE predicate on the "link_last_seen" field.
func LinkLastSeenLTE(v time.Time) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldLTE(FieldLinkLastSeen, v))
}

// LinkLastSeenIsNil applies the IsNil predicate on the "link_last_seen" field.
func LinkLastSeenIsNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldIsNull(FieldLinkLastSeen))
}

// LinkLastSeenNotNil applies the NotNil predicate on the "link_last_seen" field.
func LinkLastSeenNotNil() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.FieldNotNull(FieldLinkLastSeen))
}

// HasInterface applies the HasEdge predicate on the "interface" edge.
func HasInterface() predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InterfaceTable, InterfaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInterfaceWith applies the HasEdge predicate on the "interface" edge with a given conditions (other predicates).
func HasInterfaceWith(preds ...predicate.DeviceInterface) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(func(s *sql.Selector) {
		step := newInterfaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceInterfaceLink) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceInterfaceLink) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceInterfaceLink) predicate.DeviceInterfaceLink {
	return predicate.DeviceInterfaceLink(sql.NotPredicates(p))
}
