// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-ipam/internal/cert"
	"github.com/go-tangra/go-tangra-ipam/internal/client"
	"github.com/go-tangra/go-tangra-ipam/internal/data"
	"github.com/go-tangra/go-tangra-ipam/internal/event"
	"github.com/go-tangra/go-tangra-ipam/internal/kvm"
	"github.com/go-tangra/go-tangra-ipam/internal/metrics"
	"github.com/go-tangra/go-tangra-ipam/internal/server"
	"github.com/go-tangra/go-tangra-ipam/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	auditLogRepo := data.NewAuditLogRepo(context, entClient)
	dnsConfigRepo := data.NewDnsConfigRepo(context, entClient)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	systemService := service.NewSystemService(context, dnsConfigRepo, statisticsRepo)
	subnetRepo := data.NewSubnetRepo(context, entClient)
	ipScanJobRepo := data.NewIpScanJobRepo(context, entClient)
	subnetService := service.NewSubnetService(context, subnetRepo, ipScanJobRepo, collector)
	vlanRepo := data.NewVlanRepo(context, entClient)
	vlanService := service.NewVlanService(context, vlanRepo, collector)
	deviceRepo := data.NewDeviceRepo(context, entClient)
	deviceInterfaceRepo := data.NewDeviceInterfaceRepo(context, entClient)
	ipAddressRepo := data.NewIpAddressRepo(context, entClient)
	devicePackageRepo := data.NewDevicePackageRepo(context, entClient)
	registrationClient, err := client.NewRegistrationClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	moduleDialer := client.NewModuleDialer(context, registrationClient)
	wardenClient, cleanup2, err := client.NewWardenClient(context, moduleDialer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kvmService := kvm.NewService(context)
	deviceService := service.NewDeviceService(context, deviceRepo, deviceInterfaceRepo, ipAddressRepo, devicePackageRepo, wardenClient, kvmService, collector)
	locationRepo := data.NewLocationRepo(context, entClient)
	locationService := service.NewLocationService(context, locationRepo, collector)
	redisClient, cleanup3, err := data.NewRedisClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	publisher := event.NewPublisher(context, redisClient)
	ipAddressService := service.NewIpAddressService(context, ipAddressRepo, subnetRepo, collector, publisher)
	ipScanService := service.NewIpScanService(context, ipScanJobRepo, subnetRepo, ipAddressRepo)
	ipGroupRepo := data.NewIpGroupRepo(context, entClient)
	ipGroupService := service.NewIpGroupService(context, ipGroupRepo)
	hostGroupRepo := data.NewHostGroupRepo(context, entClient)
	hostGroupService := service.NewHostGroupService(context, hostGroupRepo)
	backupService := service.NewBackupService(context, entClient)
	devicePackageService := service.NewDevicePackageService(context, deviceRepo, devicePackageRepo)
	taskExecutor := service.NewTaskExecutor(context, ipScanService, subnetRepo)
	sqlBackupService := service.NewSqlBackupService(context)
	grpcServer := server.NewGRPCServer(context, certManager, collector, auditLogRepo, systemService, subnetService, vlanService, deviceService, locationService, ipAddressService, ipScanService, ipGroupService, hostGroupService, backupService, devicePackageService, taskExecutor, sqlBackupService)
	httpServer := server.NewHTTPServer(context, kvmService)
	scanExecutor := service.NewScanExecutor(context, ipScanJobRepo, subnetRepo, ipAddressRepo, deviceRepo, deviceInterfaceRepo, publisher)
	app := newApp(context, grpcServer, httpServer, scanExecutor)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
